### ISSUE TITLE
ssdd

### ISSUE THREAD

**Issue by 0Freeebaby** [open-mmlab/mmrotate#1021]
### Model/Dataset/Scheduler description

The data set I am using is ssdd, and its image type is jpg, but the error is not found... .png, can you help me with this problem？

Traceback (most recent call last):
  File "D:/studycodes/mmrotate-main/tools/train.py", line 194, in <module>
    main()
  File "D:/studycodes/mmrotate-main/tools/train.py", line 190, in main
    meta=meta)
  File "D:\studycodes\mmrotate-main\mmrotate\apis\train.py", line 144, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmdet-2.28.2-py3.7.egg\mmdet\datasets\custom.py", line 220, in __getitem__
    data = self.prepare_train_img(idx)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmdet-2.28.2-py3.7.egg\mmdet\datasets\custom.py", line 243, in prepare_train_img
    return self.pipeline(results)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmdet-2.28.2-py3.7.egg\mmdet\datasets\pipelines\compose.py", line 41, in __call__
    data = t(data)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmdet-2.28.2-py3.7.egg\mmdet\datasets\pipelines\loading.py", line 67, in __call__
    img_bytes = self.file_client.get(filename)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmcv\fileio\file_client.py", line 1017, in get
    return self.client.get(filepath)
  File "D:\Program Files\anaconda3\envs\mmrotate\lib\site-packages\mmcv\fileio\file_client.py", line 538, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/studycodes/mmrotate-main/data/ssdd/train/images/000867.png'

Process finished with exit code 1

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by 0Freeebaby** [comment]
that question I solved.This issue was fixed after I changed all the pictures in SSDD to png format.
