### ISSUE TITLE
[Bug] 执行projects目录下的RR360项目报unexpected keyword argument 'img_shape错误

### ISSUE THREAD

**Issue by yvanwy** [open-mmlab/mmrotate#1033]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0+cu113
OpenCV: 4.9.0
MMEngine: 0.10.4
MMRotate: 1.0.0rc1+fd60bef

### Reproduces the problem - code sample

(mmrotate) root@942f8j4691t7h-0:/ying.wang# /root/anaconda3/envs/mmrotate/bin/python /ying.wang/mmrotate/projects/RR360/tools/browse_dataset.py

### Reproduces the problem - command or script

(mmrotate) root@942f8j4691t7h-0:/ying.wang# /root/anaconda3/envs/mmrotate/bin/python /ying.wang/mmrotate/projects/RR360/tools/browse_dataset.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/ying.wang/mmrotate/projects/RR360/tools/browse_dataset.py", line 101, in <module>
    main()
  File "/ying.wang/mmrotate/projects/RR360/tools/browse_dataset.py", line 56, in main
    dataset = DATASETS.build(cfg.train_dataloader.dataset)
  File "/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/ying.wang/mmrotate/mmrotate/datasets/dota.py", line 46, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'img_shape'

**Comment by wokaikaixinxin** [comment]
(1)
```
vim projects/RR360/configs360/_base_/datasets/dota.py
```
(2)
将第50和67行的img_shape=(1024,1024)注释掉
(3)
保存

**Comment by wokaikaixinxin** [comment]
实际上，后续还有类似的BUG，一并修改了吧。
（1）
``` 
vim projects/RR360/configs360/rotated_rtmdet_x3_r/_base_/dota_rr.py
``` 
将第50和67行的img_shape=(1024,1024)注释掉，保存。
（2）
``` 
vim projects/RR360/configs360/rotated_rtmdet_x3/_base_/dota_rr.py
``` 
将第50和67行的img_shape=(1024,1024)注释掉，保存。
