### ISSUE TITLE
ZeroDivisionError: division by zero when angle_version = 'le90'

### ISSUE THREAD

**Issue by JY00002** [open-mmlab/mmrotate#13]
**model:**
redet_re50_refpn_1x_dota_le90.py
dataset_type = 'DOTADataset'
angle_version = 'le90'

**dataset:**
no problem when use "r3det" with  angle_version = 'oc' and dataset_type = 'DOTADataset'

**ERROR Traceback** 
RuntimeError: DataLoader worker (pid 16773) is killed by signal: Terminated. 
Traceback (most recent call last):
  File "/home/ai/yumo/ship_det/mmrotate-main/train.py", line 182, in <module>
    main()
  File "/home/ai/yumo/ship_det/mmrotate-main/train.py", line 171, in main
    train_detector(
  File "/home/ai/yumo/ship_det/mmrotate-main/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmdet-2.21.0-py3.9.egg/mmdet/core/evaluation/eval_hooks.py", line 115, in _do_evaluate
    results = multi_gpu_test(
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmdet-2.21.0-py3.9.egg/mmdet/apis/test.py", line 100, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
    self._reset(loader, first_iter=True)
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
    self._try_put_index()
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/ai/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmdet-2.21.0-py3.9.egg/mmdet/datasets/samplers/distributed_sampler.py", line 33, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero

**Comment by zytx121** [comment]
Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.

**Comment by JY00002** [comment]
> 
I made a fool of myself. If there are other people who get such error, please check your **data_root**.
