### ISSUE TITLE
demo test environment

### ISSUE THREAD

**Issue by wq1108** [open-mmlab/mmrotate#133]
Traceback (most recent call last):
  File "demo/image_demo.py", line 42, in <module>
    main()
  File "demo/image_demo.py", line 33, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/wenqing/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 32, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/home/wenqing/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 335, in fromfile
    use_predefined_variables)
  File "/home/wenqing/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 181, in _file2dict
    check_file_exist(filename)
  File "/home/wenqing/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/wenqing/mmrotate-main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_v3.py" does not exist

Is this the problem of environment configuration? Thanks

**Comment by yangxue0827** [comment]
obvious error：
`FileNotFoundError: file "/home/wenqing/mmrotate-main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_v3.py" does not exist
`

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/158052679-0df88ec5-e488-4c44-84c5-b6111f943ca0.png)
we did not provide `oriented_rcnn_r50_fpn_1x_dota_v3.py`

**Comment by wq1108** [comment]
ok, thanks. no weight, no  oriented_rcnn_r50_fpn_1x_dota_v3.py
