### ISSUE TITLE
Support get flops tool.

### ISSUE THREAD

**Issue by so-bright** [open-mmlab/mmrotate#145]
在对Oriented RCNN使用get flops工具计算参数量时出现错误
(torch1.7) ubuntu@ml-ubuntu20-04-desktop-v2-2-32gb-25m:~/mmrotate$ python tools/analysis_tools/get_flops.py configs/oriented_rcnn/oriented_rcnn_r50_fpn_6x_ssdd_le90.py 
/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmdet-2.22.0-py3.7.egg/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 97, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 82, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/cnn/utils/flops_counter.py", line 105, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/detectors/two_stage.py", line 86, in forward_dummy
    roi_outs = self.roi_head.forward_dummy(x, proposals)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 87, in forward_dummy
    bbox_results = self._bbox_forward(x, rois)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 170, in _bbox_forward
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py", line 289, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/ops/roi_align_rotated.py", line 171, in forward
    self.clockwise)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/ops/roi_align_rotated.py", line 70, in forward
    clockwise=ctx.clockwise)
RuntimeError: wrong roi size
(torch1.7) ubuntu@ml-ubuntu20-04-desktop-v2-2-32gb-25m:~/mmrotate$ python tools/analysis_tools/get_flops.py configs/oriented_rcnn/1.py 
/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmdet-2.22.0-py3.7.egg/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 97, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 82, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/cnn/utils/flops_counter.py", line 105, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/detectors/two_stage.py", line 86, in forward_dummy
    roi_outs = self.roi_head.forward_dummy(x, proposals)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 87, in forward_dummy
    bbox_results = self._bbox_forward(x, rois)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 170, in _bbox_forward
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmrotate-0.1.0-py3.7.egg/mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py", line 289, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/ops/roi_align_rotated.py", line 171, in forward
    self.clockwise)
  File "/home/ubuntu/anaconda3/envs/torch1.7/lib/python3.7/site-packages/mmcv/ops/roi_align_rotated.py", line 70, in forward
    clockwise=ctx.clockwise)
RuntimeError: wrong roi size

**Comment by zytx121** [comment]
Hi @so-bright 
We do not provide a tool to calculate flops now.  And the get flops tool of mmdet does not support the rotated operators.

**Comment by so-bright** [comment]
Is there a plan to support get flops tool in the future?

**Comment by zytx121** [comment]
Of course, we also welcome PR from the community.

**Comment by yangxue0827** [comment]
PR https://github.com/open-mmlab/mmrotate/pull/176 is in progress
