### ISSUE TITLE
Problems on "rbbox_overlaps" function

### ISSUE THREAD

**Issue by YimingDong1999** [open-mmlab/mmrotate#154]
Now I'm implementing a model where "rbbox_overlaps" function is used (for computing the iou loss between predicted rotated bbox and ground truths). The predicted rotated bbox is a torch tensor with shape [100, 5] which serves as the parameter "bboxes1", and the gt bbox is a torch tensor with shape [11, 5] serving as the parameter "bboxes2". But I've encountered the following error message:

```
Traceback (most recent call last):
  File "/home1/ymdong/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home1/ymdong/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home1/ymdong/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home1/ymdong/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home1/ymdong/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home1/ymdong/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home1/ymdong/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home1/ymdong/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ymdong/mmrotate/tools/train.py", line 182, in <module>
    main()
  File "/home/ymdong/mmrotate/tools/train.py", line 171, in main
    train_detector(
  File "/home1/ymdong/mmrotate/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in  _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home1/ymdong/mmrotate/mmrotate/models/detectors/single_stage.py", line 82, in forward_train
    losses = self.bbox_head.forward_train(x, img_metas, gt_bboxes,
  File "/home1/ymdong/mmrotate/mmrotate/models/dense_heads/detr.py", line 576, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home1/ymdong/mmrotate/mmrotate/models/dense_heads/detr.py", line 316, in loss
    losses_cls, losses_bbox = multi_apply(
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home1/ymdong/mmrotate/mmrotate/models/dense_heads/detr.py", line 365, in loss_single
    cls_reg_targets = self.get_targets(cls_scores_list, bbox_preds_list,
  File "/home1/ymdong/mmrotate/mmrotate/models/dense_heads/detr.py", line 465, in get_targets
    bbox_weights_list, pos_inds_list, neg_inds_list) = multi_apply(
  File "/home1/ymdong/anaconda3/lib/python3.8/site-packages/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home1/ymdong/mmrotate/mmrotate/models/dense_heads/detr.py", line 508, in _get_target_single
    assign_result = self.assigner.assign(bbox_pred, cls_score, gt_bboxes,
  File "/home1/ymdong/mmrotate/mmrotate/core/bbox/assigners/rotated_hungarian_assigner.py", line 125, in assign
    iou_cost = self.iou_cost(bbox_pred, normalize_gt_bboxes)
  File "/home1/ymdong/mmrotate/mmrotate/core/bbox/match_costs/match_cost.py", line 20, in __call__
    overlaps = rbbox_overlaps(
  File "/home1/ymdong/mmrotate/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 74, in rbbox_overlaps
    bboxes1[2:4].clamp_(min=1e-3)
RuntimeError: Output 0 of SliceBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

As "bboxes1" is included in gradient computation (bboxes1.grad_fn = <SelectBackward object at 0x7fcea7101190>) and "bboxes2" is excluded (it is the ground truth), when clamping on this the Python would return this error message. Should I create a deep copy before calling this function? Are there any better methods?

What's more, it is likely that there are some bugs in the twice calling of "clamp_" method. (/mmrotate/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py, line 74 and 75) I find that in "tests/test_utils/test_overlaps.py" there is a pytest session for testing the "rbbox_overlaps" function. Here it is given two tensors "predict" and "gt", but after running the code
`bboxes1[2:4].clamp_(min=1e-3)`
the variable "bboxes1" becomes
`tensor([[ 9.0334e+02,  1.0344e+03,  1.8100e-07,  1.0000e-07, -3.1200e-01],
        [ 9.0334e+02,  1.0344e+03,  1.0000e-07,  1.0000e-03, -3.1200e-01],
        [ 9.0334e+02,  1.0344e+03,  1.8100e+07,  1.0000e+07,  1.0000e-03]])`
So indeed it is clamping on the second to the fourth row, instead of clamping the third and fourth element in each row which is ought to be. And there are the same problem in "bboxes2".

So I wanna know whether it is indeed a bug and get a solution to the problem indicated by the error message. Thanks in advance.

**Comment by yangxue0827** [comment]
Thanks, this is a bug.

**Comment by yangxue0827** [comment]
You are welcome to submit a PR to fix it.

**Comment by zytx121** [comment]
Hi @YimingDong1999
I guess you want to implement a loss function similar to IOU loss, but unfortunately, you can't. Because this CUDA operator cannot return the gradient. You need to use a differentiable operator like https://github.com/csuhan/s2anet/blob/master/configs/rotated_iou/README.md

**Comment by YimingDong1999** [comment]
> Hi @YimingDong1999 I guess you want to implement a loss function similar to IOU loss, but unfortunately, you can't. Because this CUDA operator cannot return the gradient. You need to use a differentiable operator like https://github.com/csuhan/s2anet/blob/master/configs/rotated_iou/README.md.
> 
> We have planned to add it to mmcv. #114 You are welcome to submit a PR.

But I still reserve the opinion that one may not modify the function parameters in computation.
```
def rbbox_overlaps(bboxes1, bboxes2, mode='iou', is_aligned=False):
    """Calculate overlap between two set of bboxes.

    Args:
        bboxes1 (torch.Tensor): shape (B, m, 5) in <cx, cy, w, h, a> format
            or empty.
        bboxes2 (torch.Tensor): shape (B, n, 5) in <cx, cy, w, h, a> format
            or empty.
        mode (str): "iou" (intersection over union), "iof" (intersection over
            foreground) or "giou" (generalized intersection over union).
            Default "iou".
        is_aligned (bool, optional): If True, then m and n must be equal.
            Default False.
    Returns:
        Tensor: shape (m, n) if ``is_aligned`` is False else shape (m,)
    """
    assert mode in ['iou', 'iof']
    # Either the boxes are empty or the length of boxes's last dimension is 5
    assert (bboxes1.size(-1) == 5 or bboxes1.size(0) == 0)
    assert (bboxes2.size(-1) == 5 or bboxes2.size(0) == 0)

    # resolve `rbbox_overlaps` abnormal when input rbbox is too small.
    clamped_bboxes1 = torch.cat(
        (bboxes1[:, 0:2], bboxes1[:, 2:4].clamp(min=1e-3), bboxes1[:, 4:]), dim=1)
    clamped_bboxes2 = torch.cat(
        (bboxes2[:, 0:2], bboxes2[:, 2:4].clamp(min=1e-3), bboxes2[:, 4:]), dim=1)

    rows = bboxes1.size(0)
    cols = bboxes2.size(0)
    if is_aligned:
        assert rows == cols

    if rows * cols == 0:
        return bboxes1.new(rows, 1) if is_aligned else bboxes1.new(rows, cols)

    return box_iou_rotated(clamped_bboxes1, clamped_bboxes2, mode, is_aligned)
```

**Comment by yangxue0827** [comment]
Thanks for your suggestion, we will evaluate it.

**Comment by zytx121** [comment]
Hi @adonis-dym 
Discuss is welcome in #155.
