### ISSUE TITLE
get_cls_results TypeError: list indices must be integers or slices, not tuple 

### ISSUE THREAD

**Issue by xypu98** [open-mmlab/mmrotate#169]
When I try to evaluate the val dataset by mAP. The command is: ./tools/dist_test.sh ./configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py ./work_dirs/orcnn/epoch_48.pth 1 --work-dir ./work_dirs/orcnn/ --eval mAP

The error shows the /mmrotate.core/evaution/eval_map.py line 117：get_cls_results 
TypeError: list indices must be integers or slices, not tuple 

What's wrong with the evaluation? Thanks!

Traceback (most recent call last):
  File "/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed  File "/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distribute  rdzv_backend     : static  max_restarts     : 3INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchel  role_ranks=[0]ed tensors and all their associated APIs are an experimental feature and subject to change. Please/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "    det_results, annotations, i)  

File "/remote-home/pxy/mmrotate/mmrotate/core/evaluation/eval_map.py", line 117, in get_cls_resuTypeError: list indices must be integers or slices, not tuple** 
 restart_count=1  group_rank=0  global_world_sizes=[1]
^CTraceback (most recent call last):    "__main__", mod_spec)d/launch.py", line 173, in <module>
(openmmlab) pxy@7a259c32fc9e:~/mmrotate$ ./tools/dist_test.sh ./configs/oriented_rcnn/oriented_rcn  max_restarts     : 3INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchel  role_ranks=[0]/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "    nproc=nproc)    det_results, annotations, i)  File "/remote-home/pxy/mmrotate/mmrotate/core/evaluation/eval_map.py", line 117, in get_cls_resuTypeError: list indices must be integers or slices, not tupleERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failedINFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group  group_rank=0INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_a4    "__main__", mod_spec)d/launch.py", line 173, in <module>

**Comment by xypu98** [comment]
I check ./configs/_base_/datasets/dotav1.py and correct the test ann_file path . It works.
