### ISSUE TITLE
training HRSV2016 with clasesswise=ture, the error : 'HRSCDataset' object has no attribute 'CLASSES_ID'

### ISSUE THREAD

**Issue by ANCYzds** [open-mmlab/mmrotate#173]
Traceback (most recent call last):
  File "/home/zds/miniconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/zds/Documents/mmrotate/mmrotate/datasets/hrsc.py", line 65, in __init__
    super(HRSCDataset, self).__init__(ann_file, pipeline, **kwargs)
  File "/home/zds/miniconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 95, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/home/zds/Documents/mmrotate/mmrotate/datasets/hrsc.py", line 111, in load_annotations
    if class_id not in self.CLASSES_ID:
AttributeError: 'HRSCDataset' object has no attribute 'CLASSES_ID'

**Comment by ANCYzds** [comment]
mmrotate/datasets/hrsc.py line111 ：
if class_id not in self.CLASSES_ID:改成if class_id not in self.HRSC_CLASSES_ID:

**Comment by yangxue0827** [comment]
Thanks. You are also welcome to help us fix this issue via PR

**Comment by liuyanyi** [comment]
Sorry, i think that's a typo, you can try
```
if class_id not in self.HRSC_CLASSES_ID:
```

**Comment by ANCYzds** [comment]
@liuyanyi 谢谢您！问题已解决。
