### ISSUE TITLE
AttributeError: 'RoIAlignRotated' object has no attribute 'output_size'

### ISSUE THREAD

**Issue by lilili-h** [open-mmlab/mmrotate#191]
bug描述：在安装之后验证demo时，报出的错误。
TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV CUDA Compiler: 10.2
CUDA Runtime 10.2
PyTorch: 1.10.2
Python: 3.7.11

日志如下：
(open-mmlab) D:\MMCV\mmrotate>python demo/image_demo.py demo/demo.jpg configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py checkpoint/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth demo/vis.jpg
D:\Anaconde3\envs\open-mmlab\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] 找不到指定的模块。
  warn(f"Failed to load image Python extension: {e}")
d:\mmcv\mmdetection\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_b
ase_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: checkpoint/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
d:\mmcv\mmdetection\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" in
stead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
Traceback (most recent call last):
  File "demo/image_demo.py", line 43, in <module>
    main()
  File "demo/image_demo.py", line 36, in main
    result = inference_detector(model, args.img)
  File "d:\mmcv\mmdetection\mmdet\apis\inference.py", line 150, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "D:\Anaconde3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconde3\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "d:\mmcv\mmdetection\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "d:\mmcv\mmdetection\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "d:\mmcv\mmrotate\mmrotate\models\detectors\two_stage.py", line 184, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "d:\mmcv\mmrotate\mmrotate\models\roi_heads\rotate_standard_roi_head.py", line 253, in simple_test
    x, img_metas, proposal_list, self.test_cfg, rescale=rescale)
  File "d:\mmcv\mmrotate\mmrotate\models\roi_heads\oriented_standard_roi_head.py", line 134, in simple_test_bboxes
    bbox_results = self._bbox_forward(x, rois)
  File "d:\mmcv\mmrotate\mmrotate\models\roi_heads\rotate_standard_roi_head.py", line 170, in _bbox_forward
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "D:\Anaconde3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconde3\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "d:\mmcv\mmrotate\mmrotate\models\roi_heads\roi_extractors\rotate_single_level_roi_extractor.py", line 105, in forward
    out_size = self.roi_layers[0].output_size
  File "D:\Anaconde3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'RoIAlignRotated' object has no attribute 'output_size'

**Comment by lilili-h** [comment]
sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce MX150
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
NVCC: Not Available
GCC: n/a
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61
,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.e
xe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO
 -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1,
 PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF,
USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.2
MMRotate: 0.2.0+b78bab2
