### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by wzz893434299** [open-mmlab/mmrotate#25]
执行训练：
```shell
python tools/train.py ./configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py 
```
发生如下错误，希望可以帮助解决
```shell
Traceback (most recent call last):
  File "tools/train.py", line 182, in <module>
    main()
  File "tools/train.py", line 178, in main
    meta=meta)
File "/home/mmrotate/mmrotate/apis/train.py", line 156, in train_detector
    return _MultiProcessingDataLoaderIter(self)
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```
卡是2080ti

环境： cuda10.2, pytorch1.71

**Comment by yangxue0827** [comment]
Refer to  https://github.com/open-mmlab/mmrotate/issues/35
