### ISSUE TITLE
huge_image_demo.py TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by poirot0805** [open-mmlab/mmrotate#276]
I want to run huge_image_demo.py to inference a huge image using mask_r-cnn（only for hbb detection）

**cmd:**
```python
python demo/huge_image_demo.py  demo/47.jpg     workdir/mask_rcnn_x101_32x4d_fpn_mstrain-poly_3x_coco.py      workdir/epoch_12.pth
```
the cfg file is from mmdetection.

**env:** torch1.6.0 + cuda10.1 + mmcv-full1.5.0 + mmdet2.20.0

but I got this：
```
load checkpoint from local path: workdir/epoch_12.pth
d:\programdata\anaconda3\mmdetection\mmdet\datasets\utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
<class 'list'>
Traceback (most recent call last):
  File "demo/huge_image_demo.py", line 72, in <module>
    main(args)
  File "demo/huge_image_demo.py", line 65, in main
    args.merge_iou_thr)
  File "d:\programdata\anaconda3\mmrotate\mmrotate\apis\inference.py", line 88, in inference_detector_by_patches
    results, windows[:, :2], iou_thr=merge_iou_thr, device=device)
  File "d:\programdata\anaconda3\mmrotate\mmrotate\core\patch\merge_results.py", line 26, in merge_results
    dets[:, :2] += offset
TypeError: list indices must be integers or slices, not tuple
```

**Comment by poirot0805** [comment]
```python
for results_pre_cls in zip(*results):
        tran_dets = []
        for dets, offset in zip(results_pre_cls, offsets):
            dets[:, :2] += offset  # dets is a list [error 1]
            tran_dets.append(dets)
        tran_dets = np.concatenate(tran_dets, axis=0) 
        # although I fixed error1 by enumerating dets, error here because tran_dets is a list
```
i'm not familiar with numpy, so i don't know the solution . T A T

**Comment by zytx121** [comment]
@jbwang1997  Please have a look.

**Comment by jbwang1997** [comment]
Hi @poirot0805. I solve this problem in pr #280. You can refer to this pr.

**Comment by poirot0805** [comment]
> Hi @poirot0805. I solve this problem in pr #280. You can refer to this pr.

Thanks! it helps a lot!
