### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by 3155827819** [open-mmlab/mmrotate#299]
Traceback (most recent call last):
  File "/home/zhx/azb/mmrotate-main/tools/train.py", line 192, in <module>
    main()
  File "/home/zhx/azb/mmrotate-main/tools/train.py", line 181, in main
    train_detector(
  File "/home/zhx/azb/mmrotate-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/zhx/anaconda3/envs/bebox/lib/python3.8/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by Josh00-Lu** [comment]
他妈的我跟你遇到一样的错误，气死了

**Comment by Josh00-Lu** [comment]
Same Problem. Shanben wo r n xianren

**Comment by yangxue0827** [comment]
Check your data path.
refer to
https://github.com/open-mmlab/mmrotate/issues/35

**Comment by yangxue0827** [comment]
A related blog: https://icode.best/i/79733546247546

**Comment by LFayL** [comment]
Same Problem.

**Comment by zhangchi621** [comment]
同样的问题，A数据集运行没问题，把A复制一遍得到B， A+B训练就报错，真奇怪
ValueError: need at least one array to concatenate

**Comment by zhangchi621** [comment]
大概率是路径问题，仔细确认，我的主路径没问题，训练和测试的子路径出问题了
