### ISSUE TITLE
RuntimeError: RuntimeErrorThe size of tensor a (17) must match the size of tensor b (16) at non-singleton dimension 1: 

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#327]
When I ran the ROI TRANS in the config, I reported the following errors after all training, these are detailed errors

2022-05-30 16:08:37,018 - mmrotate - INFO - Epoch [12][3200/3200]       lr: 1.000e-06, eta: 0:00:00, time: 0.477, data_time: 0.006, memory: 11828, loss_rpn_cls: 0.0114, loss_rpn_bbox: 0.0178, s0.loss_cls: 0.0843, s0.acc: 96.4971, s0.loss_bbox: 0.0968, s1.loss_cls: 0.0904, s1.acc: 96.2743, s1.loss_bbox: 0.2311, loss: 0.5317, grad_norm: 3.4005
2022-05-30 16:08:41,068 - mmrotate - INFO - Saving checkpoint at 12 epochs
[                                                  ] 0/12800, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/train.py", line 184, in <module>
    main()
  File "./tools/train.py", line 173, in main
    train_detector(
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
Traceback (most recent call last):
  File "./tools/train.py", line 184, in <module>
    main()
  File "./tools/train.py", line 173, in main
    train_detector(
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    self.call_hook('after_train_epoch')
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    getattr(hook, fn_name)(self)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 117, in _do_evaluate
    self._do_evaluate(runner)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 117, in _do_evaluate
        results = multi_gpu_test(results = multi_gpu_test(

  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/apis/test.py", line 109, in multi_gpu_test
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
      File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
result = model(return_loss=False, rescale=True, **data)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
      File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
return old_func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
        return self.forward_test(img, img_metas, **kwargs)return self.forward_test(img, img_metas, **kwargs)

  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
      File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/detectors/two_stage.py", line 183, in simple_test
return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/detectors/two_stage.py", line 183, in simple_test
    return self.roi_head.simple_test(
      File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 321, in simple_test
return self.roi_head.simple_test(
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 321, in simple_test
    cls_score = [
      File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 322, in <listcomp>
cls_score = [
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 322, in <listcomp>
    sum([score[i] for score in ms_scores]) / float(len(ms_scores))
    sum([score[i] for score in ms_scores]) / float(len(ms_scores))
RuntimeError: RuntimeErrorThe size of tensor a (17) must match the size of tensor b (16) at non-singleton dimension 1: 
The size of tensor a (17) must match the size of tensor b (16) at non-singleton dimension 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26158) of binary: /home/dell/anaconda3/envs/zly/bin/python

May I ask what is the reason

**Comment by milamiqi** [comment]
_base_ = './roi_trans_swin_tiny_fpn_1x_dota_le90.py'


# 1. dataset settings
dataset_type = 'DOTADataset'
classes = ('plane', 'ship', 'storage-tank', 'baseball-diamond', 'tennis-court',
           'basketball-court', 'ground-track-field', 'harbor', 'bridge', 'small-vehicle',
           'large-vehicle', 'helicopter', 'roundabout', 'soccer-ball-field', 'swimming-pool', 'container-crane')

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/home/dell/Research/zly/mmrotate-main/data/DOTA/trainval/annfiles',
        img_prefix='/home/dell/Research/zly/mmrotate-main/data/DOTA/trainval/images'),
    val=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/home/dell/Research/zly/mmrotate-main/data/DOTA/trainval/annfiles',
        img_prefix='/home/dell/Research/zly/mmrotate-main/data/DOTA/trainval/images'),
    test=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='/home/dell/Research/zly/mmrotate-main/data/DOTA/testspilt/images',
        img_prefix='/home/dell/Research/zly/mmrotate-main/data/DOTA/testspilt/images'))


this is my costom.py

**Comment by zytx121** [comment]
How many GPU do you use? You can try to test with 1 GPU.

**Comment by milamiqi** [comment]
Thank you for your suggestion！！ I ran it with two GPUs. Sorry for the wrong reply to the last reply.

**Comment by milamiqi** [comment]
I still get an error when using one GPU, is there any other reason？

**Comment by zytx121** [comment]
What command do you use to run?

**Comment by milamiqi** [comment]
python tools/train.py /home/dell/Research/zly/mmrotate-main/configs/roi_trans/costom_roi_trans.py

**Comment by milamiqi** [comment]
2022-05-31 04:07:41,483 - mmrotate - INFO - Epoch [12][6350/6400]       lr: 5.000e-05, eta: 0:00:16, time: 0.321, data_time: 0.006, memory: 8660, loss_rpn_cls: 0.0104, loss_rpn_bbox: 0.0160, s0.loss_cls: 0.0902, s0.acc: 96.4336, s0.loss_bbox: 0.0845, s1.loss_cls: 0.0949, s1.acc: 96.3595, s1.loss_bbox: 0.2327, loss: 0.5287, grad_norm: 3.1541
2022-05-31 04:07:57,557 - mmrotate - INFO - Exp name: costom_roi_trans.py
2022-05-31 04:07:57,558 - mmrotate - INFO - Epoch [12][6400/6400]       lr: 5.000e-05, eta: 0:00:00, time: 0.321, data_time: 0.006, memory: 8660, loss_rpn_cls: 0.0102, loss_rpn_bbox: 0.0185, s0.loss_cls: 0.0849, s0.acc: 96.5234, s0.loss_bbox: 0.0951, s1.loss_cls: 0.0935, s1.acc: 96.2239, s1.loss_bbox: 0.2296, loss: 0.5317, grad_norm: 3.0750
2022-05-31 04:07:57,715 - mmrotate - INFO - Saving checkpoint at 12 epochs
[                                                  ] 0/12800, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 184, in <module>
    main()
  File "tools/train.py", line 173, in main
    train_detector(
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/apis/test.py", line 29, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/detectors/two_stage.py", line 183, in simple_test
    return self.roi_head.simple_test(
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 321, in simple_test
    cls_score = [
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/models/roi_heads/roi_trans_roi_head.py", line 322, in <listcomp>
    sum([score[i] for score in ms_scores]) / float(len(ms_scores))
RuntimeError: The size of tensor a (17) must match the size of tensor b (16) at non-singleton dimension 1

**Comment by milamiqi** [comment]
The error was reported when my training was done, so I tried again with the single GPU command

**Comment by zytx121** [comment]
I noticed that you modified the original ROI Trans. We need more information about what you modified

**Comment by milamiqi** [comment]
_base_ = [
    '../_base_/datasets/dotav1.py', '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]

angle_version = 'le90'
model = dict(
    type='RoITransformer',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RotatedRPNHead',
        in_channels=256,
        feat_channels=256,
        version=angle_version,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    roi_head=dict(
        type='RoITransRoIHead',
        version=angle_version,
        num_stages=2,
        stage_loss_weights=[1, 1],
        bbox_roi_extractor=[
            dict(
                type='SingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlign', output_size=7, sampling_ratio=0),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32]),
            dict(
                type='RotatedSingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlignRotated',
                    out_size=7,
                    sample_num=2,
                    clockwise=True),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32]),
        ],
        bbox_head=[
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=15,
                bbox_coder=dict(
                    type='DeltaXYWHAHBBoxCoder',
                    angle_range=angle_version,
                    norm_factor=2,
                    edge_swap=True,
                    target_means=[0., 0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2, 1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=15,
                bbox_coder=dict(
                    type='DeltaXYWHAOBBoxCoder',
                    angle_range=angle_version,
                    norm_factor=None,
                    edge_swap=True,
                    proj_xy=True,
                    target_means=[0., 0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1, 0.5]),
                reg_class_agnostic=False,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='BboxOverlaps2D')),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='RBboxOverlaps2D')),
                sampler=dict(
                    type='RRandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(type=angle_version, iou_thr=0.1),
            max_per_img=2000)))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version=angle_version),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
data = dict(
    train=dict(pipeline=train_pipeline, version=angle_version),
    val=dict(version=angle_version),
    test=dict(version=angle_version))

optimizer = dict(lr=0.005)
I should not have changed the network

**Comment by liuyanyi** [comment]
I think you should modify `num_classes` to 16 in your config

**Comment by milamiqi** [comment]
Thank you for your answer. I made an error after changing dota1.0 to 1.5. Dota1.0 has 15 categories and 1.5 has 16. I would like to modify the number of categories as follows
