### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by colorfully-ybf** [open-mmlab/mmrotate#35]
**Environment**

TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: GCC 9.1
MMCV CUDA Compiler: 11.1
MMRotate: 0.1.0+
CUDA Runtime 11.3
PyTorch: 1.10.2
Python: 3.7.11 
GPU 0,1: GeForce RTX 3090

**Error traceback**
File "/home/deep/Libraries/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/deep/Libraries/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by DDGRCF** [comment]
same error happened

**Comment by rhj0103** [comment]
`data_root = '../datasets/split_ss_1024_dota1_0/'
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),`

并且路径是正确的：
![图片](https://user-images.githubusercontent.com/86508657/158041496-59a10059-94b0-412b-8f04-94aa19f49eff.png)

**Comment by yangxue0827** [comment]
Where is you txt files in tranval/annfiles?
![image](https://user-images.githubusercontent.com/29257168/158041588-500cbe0d-8a20-438a-90c9-0484b933acc8.png)
Please use `ss_trainval.json` instead of `ss_test.json` when you split the tranval set.

**Comment by rhj0103** [comment]
Yes, I uesd `ss_trainval.json`.

**Comment by yangxue0827** [comment]
So is there any txt files in tranval/annfiles?

**Comment by rhj0103** [comment]
Yes,I just get follow files:
![image](https://user-images.githubusercontent.com/86508657/158042295-d2a43006-b525-4145-965f-8422994cf79a.png)

**Comment by rhj0103** [comment]
Is not `patch_annfile.pkl`?

**Comment by yangxue0827** [comment]
There are only txt files, please crop the data again.

**Comment by rhj0103** [comment]
Need to convert dataset format?

**Comment by yangxue0827** [comment]
Of course no conversion is required, please follow the [readme](https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md) strictly.

**Comment by rhj0103** [comment]
OK, thank you!

**Comment by rhj0103** [comment]
I cut it according to the bus you gave, but still the same error.

**Comment by rhj0103** [comment]
![图片](https://user-images.githubusercontent.com/86508657/158044793-f73e5a62-733d-4a84-9a57-72867c7bfb49.png)

![图片](https://user-images.githubusercontent.com/86508657/158044784-c4d97d06-688a-4a72-bf49-978ab18b093a.png)
![图片](https://user-images.githubusercontent.com/86508657/158044800-17b8e3ce-c35b-4776-8d00-932ee6b4c2e7.png)
![图片](https://user-images.githubusercontent.com/86508657/158044809-c7a435ac-ca30-4fa2-9424-1d9ed6986cdc.png)

**Comment by rhj0103** [comment]
![图片](https://user-images.githubusercontent.com/86508657/158044827-58df4309-60c2-488e-837e-cb3d846f4be9.png)

**Comment by yangxue0827** [comment]
Set absolute path for data_root

**Comment by rhj0103** [comment]
I succeeded, thanks a lot.

**Comment by Lg955** [comment]
- Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main()
  File "tools/train.py", line 188, in main
    meta=meta)
  File "/dataset/lg_datacode/code/DARDet/mmdet/apis/train.py", line 176, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/dataset/lg_datacode/code/DARDet/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

when I use `./tools/dist_train.sh configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py 4`, everything is OK;  
but when use `python tools/train.py configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py`, it will cause the error.  
What will cause this?

**Comment by Lg955** [comment]
- Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main()
  File "tools/train.py", line 188, in main
    meta=meta)
  File "/dataset/lg_datacode/code/DARDet/mmdet/apis/train.py", line 176, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/lg/anaconda3/envs/dardet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/dataset/lg_datacode/code/DARDet/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

when I use `./tools/dist_train.sh configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py 4`, everything is OK;  
but when use `python tools/train.py configs/DARDet/dardet_r50_fpn_1x_dcn_rotate_train.py`, it will cause the error.  
What will cause this?

**Comment by joish-li** [comment]
Is there something wrong with dotav1.py ?
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    **train**=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    **test**=dict(
        type=dataset_type,
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))

The path of train and test is incorrect

**Comment by jiubie89** [comment]
> `data_root = '../datasets/split_ss_1024_dota1_0/' data = dict( samples_per_gpu=2, workers_per_gpu=2, train=dict( type=dataset_type, ann_file=data_root + 'trainval/annfiles/', img_prefix=data_root + 'trainval/images/', pipeline=train_pipeline), val=dict( type=dataset_type, ann_file=data_root + 'trainval/annfiles/', img_prefix=data_root + 'trainval/images/', pipeline=test_pipeline),`
> 
> 并且路径是正确的： ![图片](https://user-images.githubusercontent.com/86508657/158041496-59a10059-94b0-412b-8f04-94aa19f49eff.png)

Why is your clipping data these files, but my clipping data only contains txt files, not your.pkl files, etc., and I have changed my data_root to an absolute path, but still this error (ValueError: need at least one array to concatenate)

**Comment by 11313131** [comment]
> 设置 data_root 的绝对路径

![Image](https://github.com/user-attachments/assets/15b80a8c-ebed-4ef4-a84c-e262d349e13d)

![Image](https://github.com/user-attachments/assets/4588ea50-561c-4b8e-b166-fe6cbfcfe750)

我改成了绝对路径还是错的，这是怎么回事呢？求助

**Comment by 11313131** [comment]
> I succeeded, thanks a lot.

兄弟，能看下你的文件嘛，谢谢！
