### ISSUE TITLE
KLDRepPointsHead is not in the models registry

### ISSUE THREAD

**Issue by ssq01** [open-mmlab/mmrotate#361]
**Describe the bug**

I found that there may not be a bbox_head model for the KLDRepPointsHead in g_reppoints network.

**Reproduction**

1. What command or script did you run?

python tools/train.py configs/g_reppoints/g_reppoints_r50_fpn_1x_dota_le135.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: False
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMRotate: 0.3.1+

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 165, in main
    test_cfg=cfg.get('test_cfg'))
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/models/builder.py", line 56, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "RotatedRepPoints: 'KLDRepPointsHead is not in the models registry'"
/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/utils/setup_env.py:39: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/utils/setup_env.py:49: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
Traceback (most recent call last):
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/models/detectors/rotated_reppoints.py", line 18, in __init__
    train_cfg, test_cfg, pretrained)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/models/detectors/single_stage.py", line 35, in __init__
    self.bbox_head = build_head(bbox_head)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/models/builder.py", line 37, in build_head
    return ROTATED_HEADS.build(cfg)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'KLDRepPointsHead is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 257, in <module>
    main()
  File "./tools/test.py", line 206, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmrotate/models/builder.py", line 56, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/cluster/home/it_stu50/.conda/envs/sat/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "RotatedRepPoints: 'KLDRepPointsHead is not in the models registry'"

```none
A placeholder for trackback.
```

**Bug fix**
Adding the corresponding bbox_head is needed.

**Comment by zytx121** [comment]
It is because G-Rep’s code is not available now, we will release it ASAP.

**Comment by BUAA-Worromot** [comment]
One year has passed, has it not been released yet?

**Comment by yangxue0827** [comment]
Since the author of G-Rep has graduated and the source code is based on mmrotate 0.x that is no longer maintained, the relevant code is no longer planned to be integrated into mmrotate. If you want the relevant code, please contact the author, sorry for the inconvenience.
