### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by RexRan** [open-mmlab/mmrotate#363]
I try  get_started.md to run Rotated_RetinaNet from the following code
`python ./tools/test.py    configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le90.py   checkpoints/rotated_retinanet_obb_r50_fpn_fp16_1x_dota_le90-01de71b5.pth --format-only  --eval-options submission_dir=work_dirs/Task1_results
`
and  I face the following error

```
/home/rex/project/mmrotate/mmrotate/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/rex/project/mmrotate/mmrotate/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
load checkpoint from local path: checkpoints/rotated_retinanet_obb_r50_fpn_fp16_1x_dota_le90-01de71b5.pth
Traceback (most recent call last):
  File "./tools/test.py", line 257, in <module>
    main()
  File "./tools/test.py", line 210, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 302, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/rex/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

```

Because I use DOTAv1.5, I change the num_class=16 from the rotated_retinanet_obb_r50_fpn_1x_dota_le90.py 
And I also change the data_root as `data_root = 'data/split_ms_dota/'` from congfigs/_base_/datesets/dotav1.py

**Comment by zytx121** [comment]
The weights we provide are trained on DOTAv1.0, which only have 15 categories.
