### ISSUE TITLE
How to train a  model that only has a class?

### ISSUE THREAD

**Issue by DeepDetector** [open-mmlab/mmrotate#394]
Hello, 
I want to train a  single classification model. But I got this error:
```
Traceback (most recent call last):
  File "tools/train.py", line 193, in <module>
    main()
  File "tools/train.py", line 169, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/cv2019/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmrotate/datasets/builder.py", line 47, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "/home/cv2019/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'class1'
```
And I have add class name to `classes`:
```
dataset_type = 'DOTADataset'
classes = ('class1')
data = dict(
    train=dict(pipeline=train_pipeline, 
    version=angle_version, 
    type=dataset_type,        
    classes=classes
        ),
```
Additionly, when the number of class is two, train.py can be run:
```
dataset_type = 'DOTADataset'
classes = ('class1','class2')
data = dict(
    train=dict(pipeline=train_pipeline, 
    version=angle_version, 
    type=dataset_type,        
    classes=classes
        ),
```
So, it seems that MMrotate does not support single classification？

**Comment by zytx121** [comment]
Try to use `classes = ('class1', )` replace `classes = ('class1')`.
