### ISSUE TITLE
When I was training my dataset with r3det, what was the reason for the error of map calculation

### ISSUE THREAD

**Issue by 939979325** [open-mmlab/mmrotate#429]
When I was training my dataset with r3det, what was the reason for the error of map calculation

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1199/1199, 2.4 task/s, elapsed: 496s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 182, in <module>
    main()
  File "tools/train.py", line 171, in main
    train_detector(
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmrotate\apis\train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmdet\core\evaluation\eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 363, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmrotate\datasets\dota.py", line 197, in evaluate
    mean_ap, _ = eval_rbbox_map(
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmrotate\core\evaluation\eval_map.py", line 243, in eval_rbbox_map
    print_map_summary(
  File "E:\ANA\envs\mmrotate\lib\site-packages\mmrotate\core\evaluation\eval_map.py", line 305, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: tuple index out of range

**Comment by zytx121** [comment]
Please check the `num_classes` in `bbox_head` match with your dataset.
