### ISSUE TITLE
I meet this bug sometime when I use multi-GPU to train or test the dataset

### ISSUE THREAD

**Issue by GisRookie** [open-mmlab/mmrotate#478]
I meet this bug sometime when I use multi-GPU to train or test the dataset, here is my config。
```
dataset_type = 'DOTADataset'
data_root = 'data/split_ss_dota/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(type='RRandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
#	ann_file=data_root + 'trainval/annfiles/',
#        img_prefix=data_root + 'trainval/images/',
#        ann_file=data_root + 'val/annfiles/',
#        img_prefix=data_root + 'val/images/',
        ann_file=data_root + 'ss_test/images/',
        img_prefix=data_root + 'ss_test/images/',
        pipeline=test_pipeline))
evaluation = dict(interval=12, metric='mAP', save_best='mAP')
optimizer = dict(
    type='AdamW',
    lr=0.0002,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys=dict(
            absolute_pos_embed=dict(decay_mult=0.0),
            relative_position_bias_table=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0))))
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='exp',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    warmup_by_epoch=True)
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=2)
log_config = dict(
    interval=100,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
angle_version = 'oc'
norm_cfg = dict(type='GN', ### **num_groups=32,** requires_grad=True)
model = dict(
    type='RotatedRepPoints',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True),
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=[
        dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            start_level=1,
            add_extra_convs='on_input',
            num_outs=5)
    ],
    bbox_head=dict(
        type='MYSASMRepHead',
        num_classes=15,
        in_channels=256,
        feat_channels=256,
        point_feat_channels=256,
        stacked_convs=3,
        num_points=9,
        gradient_mul=0.3,
        point_strides=[8, 16, 32, 64, 128],
        point_base_scale=2,
        norm_cfg=dict(type='GN', num_groups=32, requires_grad=True),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox_init=dict(type='ConvexGIoULoss', loss_weight=0.375),
        loss_bbox_refine=dict(type='ConvexGIoULoss', loss_weight=0.5),
        transform_method='rotrect',
        use_reassign=False,
        topk=6,
        anti_factor=0.75),
    train_cfg=dict(
        init=dict(
            assigner=dict(type='ConvexAssigner', scale=4, pos_num=1),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        refine=dict(
            assigner=dict(
                type='SASAssigner',
                topk=9,
                kld=True,
                use_ratio=True,
                new_number=35,
                ratio_mean=False,
                init=True),
            allowed_border=-1,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.3),
        max_per_img=2000))
work_dir = 'work_dir/dota/reppoints/r50_sas'
find_unused_parameters = True
auto_resume = False
gpu_ids = range(0, 1)
```

1. I have searched related issues but cannot get the expected help. yes
2. I have read the [FAQ documentation]`(https://mmrotate.readthedocs.io/en/latest/faq.html) `but cannot get the expected help. yes
3. The bug has not been fixed in the latest version. yes

```
traceback (most recent call last):
  File "tools/test.py", line 258, in <module>
    main()
  File "tools/test.py", line 231, in main
    args.gpu_collect)
  File "/home/gong/mmdetection/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/gong/mmdetection/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/gong/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/gong/mmrotate/mmrotate/models/detectors/single_stage.py", line 104, in simple_test
    *outs, img_metas, rescale=rescale)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/home/gong/mmrotate/mmrotate/models/dense_heads/my_head.py", line 1609, in get_bboxes
    rescale, with_nms, **kwargs)
  File "/home/gong/mmrotate/mmrotate/models/dense_heads/my_head.py", line 1700, in _get_bboxes_single
    poly_pred = self.points2rotrect(points_pred, y_first=True)
  File "/home/gong/mmrotate/mmrotate/models/dense_heads/my_head.py", line 445, in points2rotrect
    rotrect_pred = min_area_polygons(pts)  # Return the smallest polygons (N, 8).
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/mmcv/ops/min_area_polygons.py", line 17, in min_area_polygons
    ext_module.min_area_polygons(pointsets, polygons)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f9b6b9847d2 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x239de (0x7f9ba45699de in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x22d (0x7f9ba456b57d in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x301898 (0x7f9c20d9d898 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f9b6b96d005 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #5: <unknown function> + 0x1edf69 (0x7f9c20c89f69 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x4e5818 (0x7f9c20f81818 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: THPVariable_subclass_dealloc(_object*) + 0x299 (0x7f9c20f81b19 in /home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xfa9c8 (0x55f6a3dca9c8 in /home/gong/anaconda3/envs/torch/bin/python)
frame #9: <unknown function> + 0xfc359 (0x55f6a3dcc359 in /home/gong/anaconda3/envs/torch/bin/python)
frame #10: <unknown function> + 0xfac88 (0x55f6a3dcac88 in /home/gong/anaconda3/envs/torch/bin/python)
frame #11: <unknown function> + 0xfa6a8 (0x55f6a3dca6a8 in /home/gong/anaconda3/envs/torch/bin/python)
frame #12: <unknown function> + 0xfb128 (0x55f6a3dcb128 in /home/gong/anaconda3/envs/torch/bin/python)
frame #13: <unknown function> + 0xfb13c (0x55f6a3dcb13c in /home/gong/anaconda3/envs/torch/bin/python)
frame #14: <unknown function> + 0xfb13c (0x55f6a3dcb13c in /home/gong/anaconda3/envs/torch/bin/python)
frame #15: <unknown function> + 0xfb13c (0x55f6a3dcb13c in /home/gong/anaconda3/envs/torch/bin/python)
frame #16: <unknown function> + 0xfb13c (0x55f6a3dcb13c in /home/gong/anaconda3/envs/torch/bin/python)
frame #17: <unknown function> + 0x12b4a7 (0x55f6a3dfb4a7 in /home/gong/anaconda3/envs/torch/bin/python)
frame #18: PyDict_SetItemString + 0x89 (0x55f6a3e07a19 in /home/gong/anaconda3/envs/torch/bin/python)
frame #19: PyImport_Cleanup + 0xab (0x55f6a3e7cb8b in /home/gong/anaconda3/envs/torch/bin/python)
frame #20: Py_FinalizeEx + 0x64 (0x55f6a3ef1714 in /home/gong/anaconda3/envs/torch/bin/python)
frame #21: <unknown function> + 0x232e20 (0x55f6a3f02e20 in /home/gong/anaconda3/envs/torch/bin/python)
frame #22: _Py_UnixMain + 0x3c (0x55f6a3f0318c in /home/gong/anaconda3/envs/torch/bin/python)
frame #23: __libc_start_main + 0xf0 (0x7f9c285af840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #24: <unknown function> + 0x1d803a (0x55f6a3ea803a in /home/gong/anaconda3/envs/torch/bin/python)

[>>>>>>>>>>                              ] 2732/10833, 17.0 task/s, elapsed: 161s, ETA:   477sWARNING:torch.distributed.elastic.multiprocessing.api:Sending process 25942 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 25943) of binary: /home/gong/anaconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
tools/test.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-23_10:46:13
  host      : gong
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 25943)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 25943
======================================================
```

1. What command or script did you run?

`tools/dist_test.sh work_dir/dota/r50_rotate_reppoints.py  work_dir/dota/reppoints/r50_sas/epoch_12.pth 2 --format-only   --eval-options submission_dir=work_dir/dota/Task1_results `

2. Did you make any modifications on the code or config? Did you understand what you have modified?                                                `I just modify code in the head part, and  I usually train or test successfully on my own dataset or other. Besides, this bug happen with no regularity, and the most possible situation it occur is in the stage of validation and test.`
3. What dataset did you use?
`DOTA1.0`

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.6.0
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMRotate: 0.3.2+c62f148

```

**Comment by zytx121** [comment]
We recommend you use one card to test.

**Comment by GisRookie** [comment]
When use one card to test, I meet a new problem as follow:
`[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3066/3066, 5.4 task/s, elapsed: 568s, ETA:     0s
+--------------------+-------+-------+--------+-----------+-------+
| class              | gts   | dets  | recall | precision | ap    |
+--------------------+-------+-------+--------+-----------+-------+
| plane              | 4449  | 22061 | 0.940  | 0.190     | 0.889 |
| baseball-diamond   | 358   | 6426  | 0.880  | 0.049     | 0.738 |
| bridge             | 783   | 0     | 0.000  | 0.000     | 0.000 |
| ground-track-field | 212   | 0     | 0.000  | 0.000     | 0.000 |
| small-vehicle      | 10579 | 0     | 0.000  | 0.000     | 0.000 |
| large-vehicle      | 8819  | 0     | 0.000  | 0.000     | 0.000 |
| ship               | 18537 | 0     | 0.000  | 0.000     | 0.000 |
| tennis-court       | 1512  | 0     | 0.000  | 0.000     | 0.000 |
| basketball-court   | 266   | 0     | 0.000  | 0.000     | 0.000 |
| storage-tank       | 4740  | 0     | 0.000  | 0.000     | 0.000 |
| soccer-ball-field  | 251   | 0     | 0.000  | 0.000     | 0.000 |
| roundabout         | 275   | 0     | 0.000  | 0.000     | 0.000 |
| harbor             | 4167  | 0     | 0.000  | 0.000     | 0.000 |
| swimming-pool      | 732   | 0     | 0.000  | 0.000     | 0.000 |
| helicopter         | 122   | 0     | 0.000  | 0.000     | 0.000 |
+--------------------+-------+-------+--------+-----------+-------+
| mAP                |       |       |        |           | 0.108 |
+--------------------+-------+-------+--------+-----------+-------+
`

**Comment by GisRookie** [comment]
When I use one card to test, I meet a the problem as follow:
![image](https://user-images.githubusercontent.com/93173394/186106776-6bebfaae-0503-4e15-8005-e074e21230ef.png)

**Comment by GisRookie** [comment]
And here is my test command
`python tools/test.py work_dir/dota/r50_rotate_reppoints.py work_dir/dota/reppoints/r50_sas/epoch_12.pth --eval mAP`

**Comment by zytx121** [comment]
Have you ever modified the `bbox_head.num_classes` in the config?

**Comment by GisRookie** [comment]
Yes, and the val stage outputs correctly。

**Comment by zytx121** [comment]
Do you mean the evaluation results in the val stage are correct, but the evaluation results were wrong in the test stage? Please check the output of `MYSASMRepHead` is right. It looks like the output only has 2 classes.
