### ISSUE TITLE
Some file path issues

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#485]
I see settings like below in my project
         loss_cls=dict(
             type='FocalLoss',
But I can't find the specific code of FL, where is it?
There are other loss functions in mmeotate/model/loss, but they cannot be simply replaced

**Comment by liuyanyi** [comment]
you can check https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/losses/focal_loss.py

**Comment by milamiqi** [comment]
thank you for your help!

**Comment by milamiqi** [comment]
I get an error when I replace the loss function with BalancedL1Loss when using s2anet
AssertionError, I can't find the reason, can you please explain why?

**Comment by milamiqi** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 184, in <module>
    main()
  File "tools/train.py", line 173, in main
    train_detector(
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmrotate/models/detectors/s2anet.py", line 87, in forward_train
    loss_base = self.fam_head.loss(
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmrotate/models/dense_heads/rotated_anchor_head.py", line 502, in loss
    losses_cls, losses_bbox = multi_apply(
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmrotate/models/dense_heads/rotated_anchor_head.py", line 427, in loss_single
    loss_cls = self.loss_cls(
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/losses/balanced_l1_loss.py", line 114, in forward
    loss_bbox = self.loss_weight * balanced_l1_loss(
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/parrots_jit.py", line 22, in wrapper_inner
    return func(*args, **kargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/losses/utils.py", line 101, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmdet/models/losses/balanced_l1_loss.py", line 44, in balanced_l1_loss
    assert pred.size() == target.size()
AssertionError

**Comment by milamiqi** [comment]
model = dict(
    fam_head=dict(
        loss_cls=dict(
            _delete_='True',
            type='BalancedL1Loss'
        )
    ),
    odm_head=dict(
        loss_cls=dict(
            _delete_='True',
            type='BalancedL1Loss',
        )
                    )
)

**Comment by zytx121** [comment]
Please check your loss input. `SmoothL1Loss` also has the assert of  `pred.size() == target.size()`

**Comment by yangxue0827** [comment]
Find the corresponding paper.
