### ISSUE TITLE
Some problems with custom files

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#498]
The custom file can modify the parameters without modifying the source file, but when I copy the settings of the original file to the custom file, an error will be reported, and I have not modified anything

**Comment by milamiqi** [comment]
This is the corresponding error

Traceback (most recent call last):
  File "tools/train.py", line 184, in <module>
    main()
  File "tools/train.py", line 80, in main
    cfg = Config.fromfile(args.config)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/config.py", line 337, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/config.py", line 207, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp01c6ovtx/tmpy0pnlb8l.py", line 61, in <module>
NameError: name 'angle_version' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f475f451790>
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/tempfile.py", line 441, in __del__
    self.close()
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/tempfile.py", line 437, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp01c6ovtx/tmpy0pnlb8l.py'

**Comment by ziippy** [comment]
Your error is about NameError: name 'angle_version' is not defined

so, you must define angle_version

```
{angle version}: like oc, le135, or le90.
```

For, example like that

```
angle_version = 'oc'  # The angle version
model = dict(
    type='RotatedRetinaNet',  # The name of detector
    backbone=dict(  # The config of backbone
        type='ResNet',  # The type of the backbone
        depth=50,  # The d
```

**Comment by milamiqi** [comment]
thank you very much!
