### ISSUE TITLE
RuntimeError: DataLoader worker (pid ...) is killed by signal: Killed

### ISSUE THREAD

**Issue by ziippy** [open-mmlab/mmrotate#501]
I prepare the DOTA-v1.0 multi-scale patch images as your guide
https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md 

and I set the dataset config like below

```
data_root = '../dl_data/DOTA-v1.0-v1.5/split_ms_dota/'
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))
```

after then, I just learn using 'oriented_rcnn_r50_fpn_1x_dota_le90.py'

The first epoch ended successfully.
after in progressing second epoch then, I got a error messge like below

```
임시

2022-09-07 01:57:52,305 - mmrotate - INFO - Epoch [2][3000/8541]        lr: 1.000e-04, eta: 11:31:27, time: 0.453, data_time: 0.008, memory: 17024, loss_rpn_cls: 0.0167, loss_rpn_bbox: 0.0730, loss_cls: 0.1363, acc: 94.4897, loss_bbox: 0.1394, loss: 0.3655, grad_norm: 2.5769
2022-09-07 01:57:56,850 - mmrotate - INFO - Epoch [2][3010/8541]        lr: 1.000e-04, eta: 11:31:22, time: 0.454, data_time: 0.008, memory: 17024, loss_rpn_cls: 0.0199, loss_rpn_bbox: 0.0492, loss_cls: 0.1182, acc: 95.3809, loss_bbox: 0.1227, loss: 0.3100, grad_norm: 2.5161
2022-09-07 01:58:01,550 - mmrotate - INFO - Epoch [2][3020/8541]        lr: 1.000e-04, eta: 11:31:19, time: 0.470, data_time: 0.008, memory: 17024, loss_rpn_cls: 0.0199, loss_rpn_bbox: 0.0545, loss_cls: 0.1632, acc: 93.2617, loss_bbox: 0.1576, loss: 0.3952, grad_norm: 2.5662
2022-09-07 01:58:06,026 - mmrotate - INFO - Epoch [2][3030/8541]        lr: 1.000e-04, eta: 11:31:14, time: 0.448, data_time: 0.008, memory: 17024, loss_rpn_cls: 0.0154, loss_rpn_bbox: 0.0491, loss_cls: 0.1361, acc: 94.5972, loss_bbox: 0.1257, loss: 0.3263, grad_norm: 2.3523
Traceback (most recent call last):
  File "./tools/train.py", line 192, in <module>
    main()
  File "./tools/train.py", line 181, in main
    train_detector(
  File "/home/jovyan/playGround/ziippy/mmrotate/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 61, in after_train_iter
    runner.outputs['loss'].backward()
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1169953) is killed by signal: Killed. 
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1157348 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1157349 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1157350 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1157347) of binary: /opt/conda/envs/mmrotate/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/mmrotate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/mmrotate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/mmrotate/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-07_01:58:12
  host      : air-research-ziippy-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1157347)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

one more try learning -> still error.
why DataLoader worker (pid 1169953) is killed by signal: Killed. ?

What's the reason?
please help me.

**Comment by ziippy** [comment]
I find the reason myself.
because Pytorch using many PC memory when distributed processing.

Before my machine, 4 core / 16G memry
After change my machine to 4 core / 24G memory

and now I did not see the "RuntimeError: DataLoader worker..."

so, If you got a killed error. you first check your memory spec.
