### ISSUE TITLE
ReResNet: self.in_type should depend on in_channels

### ISSUE THREAD

**Issue by tilmann-bartsch** [open-mmlab/mmrotate#518]
Is there a reason that in [this](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/models/backbones/re_resnet.py#L476) line we have
```
self.in_type = build_enn_trivial_feature(3)
```
intead of 
```
self.in_type = build_enn_trivial_feature(in_channels)
```
Due to this it seems that I am not able to instantiate [ReDet](https://github.com/open-mmlab/mmrotate/blob/main/configs/redet/redet_re50_refpn_1x_dota_le90.py) with the following backbone.
```
backbone=dict(
    type='ReResNet',
    in_channels=10,
    depth=50,
    num_stages=4,
    out_indices=(0, 1, 2, 3),
    frozen_stages=1,
    style='pytorch',
    pretrained='work_dirs/pretrain/re_resnet50_c8_batch256-25b16846.pth'),
```

**Comment by zytx121** [comment]
Sorry, we don't try it before. What error does it raise?

**Comment by tilmann-bartsch** [comment]
I stumble upon the issue the following way:

1. I implemented and registered a dataset and pipeline step to be able to read images with more than 3 channels from `.npy`-files. ([code](https://gist.github.com/tilmann-bartsch/5ee07afa4dd136bbcbf9fee32f0482e2))

2. Then I train the model using [this](https://gist.github.com/tilmann-bartsch/70be94cbfdeb946f6a4974f0272096b0) config.

3. This leads to the error
```
Traceback (most recent call last):
  File "/home/tbartsch/predict-bbox/mmrotate_models/benchmark.py", line 66, in main
    train_and_evaluate(cfg.data_directory)
  File "/home/tbartsch/predict-bbox/mmrotate_models/benchmark.py", line 56, in train_and_evaluate
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmcv/parallel/data_parallel.py", line 60, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmrotate/models/detectors/two_stage.py", line 127, in forward_train
    x = self.extract_feat(img)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmrotate/models/detectors/two_stage.py", line 67, in extract_feat
    x = self.backbone(img)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/mmrotate/models/backbones/re_resnet.py", line 591, in forward
    x = enn.GeometricTensor(x, self.in_type)
  File "/home/tbartsch/predict-bbox/venv/lib/site-packages/e2cnn/nn/geometric_tensor.py", line 164, in __init__
    assert tensor.shape[1] == type.size, \
AssertionError: Error! The size of the tensor torch.Size([2, 18, 1024, 1024]) does not match the size of the field type 3.
```

**Comment by zytx121** [comment]
In your error report, the second channel of `x`  is 18, but `in_channels` is 3.  You should use `self.in_type = build_enn_trivial_feature(in_channels)` here.
