### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcls'

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#547]
Hello, I reported the following error when running the convnext model

  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmcls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/dell/anaconda3/envs/zly/lib/python3.8/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

It seems that the problem is with the MMCV version, but my mmcv is already the maximum version allowed by MMROTATE (1. 6. 0)

**Comment by milamiqi** [comment]
TorchVision: 0.12.0+cu113
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMRotate: 0.3.2+c62f148

**Comment by milamiqi** [comment]
thank you for your help!
