### ISSUE TITLE
复现demo出现ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by LUO77123** [open-mmlab/mmrotate#56]
我的版本
Python             3.9.7
mmcv               1.4.6
mmdet              2.22.0
mmrotate           0.1.0
torch              1.7.1+cu110
torchaudio         0.7.2
torchvision        0.8.2+cu110
nvcc -V显示  Cuda compilation tools, release 11.0, V11.0.194
nvidia-smi 显示 CUDA Version: 11.1

通过  1.pip install openmim 2.mim install mmrotate    命令，顺利安装成功。
创建checkpoint文件夹存放预训练模型，
测试命令  python demo/image_demo.py demo/demo.jpg configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py checkpoint/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth demo/vis.jpg device 6

报错 
Traceback (most recent call last):
  File "/home/C/LUOLIE/mmrotate-main/demo/image_demo.py", line 14, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

不知道问题出在哪里，请大佬指导一下

**Comment by Soul-Code** [comment]
同样的问题

**Comment by LUO77123** [comment]
解决了，mmcv有版本对应要求，但是又出来其他问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月2日(周三) 晚上8:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmrotate] 复现demo出现ModuleNotFoundError: No module named 'mmcv._ext' (Issue #56)




 
同样的问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangxue0827** [comment]
Refer to https://github.com/open-mmlab/mmrotate/blob/main/docs/en/faq.md

**Comment by LUO77123** [comment]
> 参考https://github.com/open-mmlab/mmrotate/blob/main/docs/en/faq.md

感谢大佬帮助，解决了mmcv版本匹配问题，demo运行出现新的问题
我的版本
Python 3.8.12
mmcv 1.4.6
mmdet 2.22.0
mmrotate 0.1.0
torch 1.7.0+cu110
torchaudio 0.7.0
torchvision 0.8.1+cu110
nvcc -V Cuda编译工具，发布11.0，V11.0.194
nvidia -smi 显示 CUDA 版本：11.1
问题：
raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RoIAlignRotated' object has no attribute 'out_size'

以下是全部内容
/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: checkpoint/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
Traceback (most recent call last):
  File "demo/image_demo.py", line 42, in <module>
    main()
  File "demo/image_demo.py", line 35, in main
    result = inference_detector(model, args.img)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 150, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/detectors/two_stage.py", line 183, in simple_test
    return self.roi_head.simple_test(
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 252, in simple_test
    det_bboxes, det_labels = self.simple_test_bboxes(
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/oriented_standard_roi_head.py", line 134, in simple_test_bboxes
    bbox_results = self._bbox_forward(x, rois)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 169, in _bbox_forward
    bbox_feats = self.bbox_roi_extractor(
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py", line 101, in forward
    out_size = self.roi_layers[0].out_size
  File "/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RoIAlignRotated' object has no attribute 'out_size'

**Comment by LUO77123** [comment]
> 参考https://github.com/open-mmlab/mmrotate/blob/main/docs/en/faq.md

感谢大佬帮助，解决了mmcv版本匹配问题，demo运行出现新的
我的版本问题
Python 3.8.12 
mmcv 1.4.6
mmcv-full 1.4.6
mmdet 2.22.0
mmrotate 0.1.0
torch 1.7.0+cu110
torchaudio 0.7.0
torchvision 0.8。 1+cu110
nvcc -V Cuda显示编译工具，发布11.0，V11.0.194
nvidia -smi CUDA 版本：11.1
问题：
raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn. modules.module.ModuleAttributeError：“RoIAlignRotated”对象没有属性“out_size”

是全部内容
/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: num_anchorsis deprecated, 为了一致性或者也num_base_priors使用
warnings.warn('DeprecationWarning: num_anchorsis deprecated, '
load checkpoint from local path: checkpoint/
orient_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth /home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads /anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use " prior_generator
" instead第 42 行，在


main()
文件“demo/image_demo.py”，第 35 行，主要
结果 = inference_detector(model, args.img)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/ mmdet/apis/inference.py”，第 150 行，inference_detector
results = model(return_loss=False, rescale=True, **data)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site -packages/torch/nn/modules/module.py”，第 727 行，在 _call_impl
结果 = self.forward(*input, **kwargs)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8 /site-packages/mmcv/runner/fp16_utils.py”，第 109 行，在 new_func
返回 old_func(*args, **kwargs)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-包/mmdet/models/detectors/base.py”，第 174 行，在前进
返回 self.forward_test(img, img_metas, **kwargs)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py”，第 147 行，在 forward_test
返回 self.simple_test(imgs[0], img_metas[0], **kwargs)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/detectors/ two_stage.py”，第 183 行，在 simple_test
返回 self.roi_head.simple_test（
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/rotate_standard_roi_head.py” ，第 252 行，在 simple_test
det_bboxes 中，det_labels = self.simple_test_bboxes(
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/orientation_standard_roi_head.py”，第 134 行，在 simple_test_bboxes
bbox_results = self._bbox_forward(x, rois)
文件中“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/rotate_standard_roi_head.py”，第169行，在_bbox_forward
bbox_feats = self.bbox_roi_extractor（
文件“/home/zhuyu /anaconda3/envs/mmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 727 行，在 _call_impl
结果 = self.forward(*input, **kwargs)
文件“/home /zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py”，第 197 行，在 new_func
返回 old_func(*args, **kwargs)
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py”，第101行，向前
out_size = self.roi_layers[0]。 out_size
文件“/home/zhuyu/anaconda3/envs/mmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 778 行，在getattr
raise ModuleAttributeError("'{}' object has没有属性 '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RoIAlignRotated' 对象没有属性 'out_size'

**Comment by zytx121** [comment]
Hi @LUO77123 
It is a bug that has been merged to the `dev` branch  but still not merged to 'main' branch #51
