### ISSUE TITLE
When I run the train.py with the config oriented_reppoints_r50_fpn_1x_dota_le135.py, it reports the error, RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by JinqingZhengTju** [open-mmlab/mmrotate#563]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.3
MMRotate: 0.3.2+c62f148
3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by JinqingZhengTju** [comment]
> Thanks for your error report and we appreciate it a lot.
> 
> **Checklist**
> 
> 1. I have searched related issues but cannot get the expected help.
> 2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
> 3. The bug has not been fixed in the latest version.
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> ```
> A placeholder for the command.
> ```
> 
> 2. Did you make any modifications on the code or config? Did you understand what you have modified?
> 3. What dataset did you use?
> 
> **Environment**
> 
> 1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
>    sys.platform: linux
>    Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
>    CUDA available: True
>    GPU 0: NVIDIA GeForce RTX 3090
>    CUDA_HOME: /usr/local/cuda
>    NVCC: Cuda compilation tools, release 11.3, V11.3.109
>    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
>    PyTorch: 1.10.2
>    PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * C++ Version: 201402
> * Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * LAPACK is enabled (usually provided by MKL)
> * NNPACK is enabled
> * CPU capability usage: AVX512
> * CUDA Runtime 11.3
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
> * CuDNN 8.2
> * Magma 2.5.2
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.11.3 OpenCV: 4.6.0 MMCV: 1.6.0 MMCV Compiler: GCC 9.4 MMCV CUDA Compiler: 11.3 MMRotate: 0.3.2+c62f148 3. You may add addition that may be helpful for locating the problem, such as
> 
> * How you installed PyTorch [e.g., pip, conda, source]
> * Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> 
> **Error traceback** If applicable, paste the error trackback here.
> 
> ```
> A placeholder for trackback.
> ```
> 
> **Bug fix** If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I don't know why the oriented reppoints and rotated reppoints have this error.  The error is reported as follows:
2022-10-29 22:43:20,313 - mmrotate - INFO - workflow: [('train', 1)], max: 12 epochs
2022-10-29 22:43:20,313 - mmrotate - INFO - Checkpoints will be saved to /media/zjq/Data/Ubuntu_Project/svd/mmrotate/work_dirs/DOTA/oriented_reppoints by HardDiskBackend.
/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1659484809535/work/aten/src/ATen/native/TensorShape.cpp:2894.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]
/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/torch/nn/functional.py:4216: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
"Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/tools/train/train_oriented_reppoints_dota.py", line 209, in <module>
main()
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/tools/train/train_oriented_reppoints_dota.py", line 205, in main
meta=meta)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/apis/train.py", line 141, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
self.run_iter(data_batch, train_mode=True, **kwargs)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
**kwargs)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
return self.module.train_step(*inputs[0], **kwargs[0])
File "/media/zjq/Data/Ubuntu_Project/svd/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
losses = self(**data)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
return old_func(*args, **kwargs)
File "/media/zjq/Data/Ubuntu_Project/svd/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
return self.forward_train(img, img_metas, **kwargs)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/models/detectors/single_stage.py", line 82, in forward_train
gt_labels, gt_bboxes_ignore)
File "/media/zjq/Data/Ubuntu_Project/svd/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/models/dense_heads/oriented_reppoints_head.py", line 925, in loss
label_channels=label_channels)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/models/dense_heads/oriented_reppoints_head.py", line 807, in get_targets
unmap_outputs=unmap_outputs)
File "/media/zjq/Data/Ubuntu_Project/svd/mmdetection/mmdet/core/utils/misc.py", line 30, in multi_apply
return tuple(map(list, zip(*map_results)))
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/models/dense_heads/oriented_reppoints_head.py", line 677, in _point_target_single
None if self.sampling else gt_labels)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/core/bbox/assigners/max_convex_iou_assigner.py", line 102, in assign
overlaps = self.convex_overlaps(gt_rbboxes, points)
File "/media/zjq/Data/Ubuntu_Project/svd/mmrotate/mmrotate/core/bbox/assigners/max_convex_iou_assigner.py", line 215, in convex_overlaps
overlaps = convex_iou(points, gt_rbboxes)
File "/home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/ops/convex_iou.py", line 51, in convex_iou
ext_module.convex_iou(pointsets, polygons, ious)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from ConvexIoUCUDAKernelLauncher at /tmp/mmcv/mmcv/ops/csrc/pytorch/cuda/convex_iou.cu:22 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f679c82f497 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::CUDAError::Error(c10::SourceLocation, std::string) + 0x30 (0x7f675bd74024 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #2: ConvexIoUCUDAKernelLauncher(at::Tensor, at::Tensor, at::Tensor) + 0x1be (0x7f675bd9cd6f in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #3: convex_iou_cuda(at::Tensor, at::Tensor, at::Tensor) + 0x69 (0x7f675bdad309 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #4: auto Dispatch<DeviceRegistry<void (*)(at::Tensor, at::Tensor, at::Tensor), &(convex_iou_impl(at::Tensor, at::Tensor, at::Tensor))>, at::Tensor const&, at::Tensor const&, at::Tensor&>(DeviceRegistry<void (*)(at::Tensor, at::Tensor, at::Tensor), &(convex_iou_impl(at::Tensor, at::Tensor, at::Tensor))> const&, char const*, at::Tensor const&, at::Tensor const&, at::Tensor&) + 0xea (0x7f675bd14e8a in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #5: convex_iou(at::Tensor, at::Tensor, at::Tensor) + 0x69 (0x7f675bd14a69 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x2a1ce1 (0x7f675bf17ce1 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x2b4ba1 (0x7f675bf2aba1 in /home/zjq/anaconda3/envs/svd/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x237 (0x4bb4e7 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #9: /home/zjq/anaconda3/envs/svd/bin/python() [0x4baf40]
frame #10: _PyEval_EvalFrameDefault + 0x469a (0x4b793a in /home/zjq/anaconda3/envs/svd/bin/python)
frame #11: _PyFunction_FastCallKeywords + 0x106 (0x4c61f6 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #12: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #13: _PyEval_EvalFrameDefault + 0x971 (0x4b3c11 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #14: _PyFunction_FastCallKeywords + 0x106 (0x4c61f6 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #15: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #16: _PyEval_EvalFrameDefault + 0xa9e (0x4b3d3e in /home/zjq/anaconda3/envs/svd/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #18: _PyFunction_FastCallKeywords + 0x29c (0x4c638c in /home/zjq/anaconda3/envs/svd/bin/python)
frame #19: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #20: _PyEval_EvalFrameDefault + 0xa9e (0x4b3d3e in /home/zjq/anaconda3/envs/svd/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #22: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #23: /home/zjq/anaconda3/envs/svd/bin/python() [0x4d5ec0]
frame #24: PyObject_Call + 0x51 (0x4d35a1 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #25: /home/zjq/anaconda3/envs/svd/bin/python() [0x580e87]
frame #26: /home/zjq/anaconda3/envs/svd/bin/python() [0x51b401]
frame #27: PySequence_Tuple + 0x16b (0x4a30cb in /home/zjq/anaconda3/envs/svd/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x570f (0x4b89af in /home/zjq/anaconda3/envs/svd/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #30: _PyFunction_FastCallKeywords + 0x29c (0x4c638c in /home/zjq/anaconda3/envs/svd/bin/python)
frame #31: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #32: _PyEval_EvalFrameDefault + 0x15d2 (0x4b4872 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #33: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #34: _PyFunction_FastCallKeywords + 0x29c (0x4c638c in /home/zjq/anaconda3/envs/svd/bin/python)
frame #35: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #36: _PyEval_EvalFrameDefault + 0x15d2 (0x4b4872 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #38: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #39: /home/zjq/anaconda3/envs/svd/bin/python() [0x4d5ec0]
frame #40: PyObject_Call + 0x51 (0x4d35a1 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x1ea8 (0x4b5148 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #42: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #43: _PyFunction_FastCallKeywords + 0x29c (0x4c638c in /home/zjq/anaconda3/envs/svd/bin/python)
frame #44: /home/zjq/anaconda3/envs/svd/bin/python() [0x4bae2f]
frame #45: _PyEval_EvalFrameDefault + 0x469a (0x4b793a in /home/zjq/anaconda3/envs/svd/bin/python)
frame #46: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #47: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #48: /home/zjq/anaconda3/envs/svd/bin/python() [0x4d5ec0]
frame #49: PyObject_Call + 0x51 (0x4d35a1 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #50: _PyEval_EvalFrameDefault + 0x1ea8 (0x4b5148 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #51: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #52: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #53: _PyEval_EvalFrameDefault + 0x1ea8 (0x4b5148 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #54: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #55: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #56: /home/zjq/anaconda3/envs/svd/bin/python() [0x4d5ec0]
frame #57: PyObject_Call + 0x51 (0x4d35a1 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #58: _PyEval_EvalFrameDefault + 0x1ea8 (0x4b5148 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #59: _PyEval_EvalCodeWithName + 0x201 (0x4b2041 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #60: _PyFunction_FastCallDict + 0x2d6 (0x4cd006 in /home/zjq/anaconda3/envs/svd/bin/python)
frame #61: _PyObject_Call_Prepend + 0x6e (0x4d1dfe in /home/zjq/anaconda3/envs/svd/bin/python)
frame #62: /home/zjq/anaconda3/envs/svd/bin/python() [0x580007]
frame #63: PyObject_Call + 0x51 (0x4d35a1 in /home/zjq/anaconda3/envs/svd/bin/python)


Process finished with exit code 1

**Comment by JinqingZhengTju** [comment]
> Please check the input of convex_iou. Illegal input causes this error.
> 
> Refer to https://github.com/open-mmlab/mmcv/blob/699398ad8697516304a2207ef248bf8d3e6e1b7b/mmcv/ops/convex_iou.py

Thanks for your reply. I will check it.
