### ISSUE TITLE
[Docs]  report errors：KeyError: "DOTADataset: 'heng'"，‘heng’ is my label_name, and my label count is one.

### ISSUE THREAD

**Issue by lyj0123** [open-mmlab/mmrotate#587]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Traceback (most recent call last):
  File "/home/caoyushe/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/caoyushe/Project/mmrotate/mmrotate/datasets/dota.py", line 51, in __init__
    super(DOTADataset, self).__init__(ann_file, pipeline, **kwargs)
  File "/home/caoyushe/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 95, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/home/caoyushe/Project/mmrotate/mmrotate/datasets/dota.py", line 106, in load_annotations
    label = cls_map[cls_name]
KeyError: 'heng'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 168, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/caoyushe/Project/mmrotate/mmrotate/datasets/builder.py", line 51, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "/home/caoyushe/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "DOTADataset: 'heng'"

**Comment by ZhuoZhangZhang** [comment]
Have you solved it yet?

**Comment by M-Chase** [comment]
I have the same problem!

**Comment by M-Chase** [comment]
I have solved this problem.
The problem happened when you install the mmrotate.
[install docs](https://mmrotate.readthedocs.io/en/latest/install.html)
if you use the case a :
`git clone https://github.com/open-mmlab/mmrotate.git`
`cd mmrotate`
`pip install -v -e .`
you need to change the classname in the file mmrotate/datasets/dota.py 
change the CLASS=() to your classname in your dataset.
else if you use the case b,when you use the case b :
`pip install mmrotate`
you need to substitute your classname to the CLASS param

**Comment by lyj0123** [comment]
I have use “ pip install mmrotate ” to install mmrotate, so could you tell me how to change the label_name in dota.py.
the label name is not the mmrotate-main/configs/base/datasets/dotav1.py .
It refers to how to modify the category name in the installation environment

**Comment by M-Chase** [comment]
> I have use “ pip install mmrotate ” to install mmrotate, so could you tell me how to change the label_name in dota.py. the label name is not the mmrotate-main/configs/base/datasets/dotav1.py . It refers to how to modify the category name in the installation environment

I think you can change the source code of the package that you installed.
or maybe you can change the class when you import  the dotav1.

**Comment by zytx121** [comment]
Hi @lyj0123 
Change the CLASS=() to your classname in your dataset, like ` CLASSES=('heng', )`
