### ISSUE TITLE
Tensor doesn't match error in CFA reassign process when using DOTA V1.0 dataset

### ISSUE THREAD

**Issue by sltlls** [open-mmlab/mmrotate#592]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Sep 13 2021, 19:43:44) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3: TITAN X (Pascal)
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.10
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.4-dev
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMRotate: 0.3.2+0edd257

### Reproduces the problem - code sample

_base_ = ['../rotated_reppoints/rotated_reppoints_r50_fpn_1x_dota_oc.py']

model = dict(
    bbox_head=dict(use_reassign=True),
    train_cfg=dict(
        refine=dict(assigner=dict(pos_iou_thr=0.1, neg_iou_thr=0.1))))

### Reproduces the problem - command or script

python tools/train.py configs/cfa/cfa_r50_fpn_1x_dota_oc.py

### Reproduces the problem - error message

2022-11-02 19:09:02,535 - mmrotate - INFO - workflow: [('train', 1)], max: 12 epochs
2022-11-02 19:09:02,535 - mmrotate - INFO - Checkpoints will be saved to /media/amax/partion2/lsy/work_dir/mmlabV1/mmrotate/convex-hull_fa/cfa_r50_fpn_1x_dota1_oc by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 188, in main
    meta=meta)
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmrotate/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amax/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmrotate/mmrotate/models/detectors/single_stage.py", line 82, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmrotate/mmrotate/models/dense_heads/rotated_reppoints_head.py", line 710, in loss
    num_level=num_level
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmdetection/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/media/amax/partion2/lsy/workspace/mmlab_V1/mmrotate/mmrotate/models/dense_heads/rotated_reppoints_head.py", line 918, in reassign
    level_gt_mask = level_mask & gt_mask
RuntimeError: The size of tensor a (2740) must match the size of tensor b (12) at non-singleton dimension 0

### Additional information

I'm using the official DOTA V1.0 dataset(oriented bbox) training cfa module(official config file) when this error occured.

I believe this error occured in the reassign function in rotated_reppoints_head.py because when traing in rotated_reppoints_r50_fpn_1x_dota_oc.py with other training setting unchanged, it worked normally and this error was not occured.

**Comment by sltlls** [comment]
ok, I've found where the peoblem is, in mmrotate/models/dense_heads/rotated_reppoints_head.py _point_target_single function line 355, the unmap function map the labels up to original set of proposals with the default fill setting of unmap func(the unmap func is in mmdet/core/utils/misc.py, and the default fill setting is 0), which is incompatible with the tensor labels because 0 is one of the gt label indexs(I checked this incompatible from the initialization of labels, which initialize labels with self.num_classes instead of 0). Thus, when labels need to be mapped up, the mapped part with 0 can not be filtered in the subsequent pos_inds generating process and caused error in reassign func.

**Comment by yellowjs0304** [comment]
@zytx121 It looks like this part is erased in latest commit. Is it okay i can modify like those?
