### ISSUE TITLE
[Bug] v1.x image_demo bboxes AttributeError: 'Tensor' object has no attribute 'convert_to'

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmrotate#611]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

Not found in dev-1.x: `python: can't open file 'mmrotate/utils/collect_env.py': [Errno 2] No such file or directory`

### Reproduces the problem - code sample

I trained the Oriented R-CNN model on the tiny SSDD example dataset for 3 epochs. I'm now attempting to run `demo/image_demo.py` on an image from the dataset (ssdd_tiny/images/000631.png), but get an error with the bboxes.

### Reproduces the problem - command or script

`python demo/image_demo.py ssdd_tiny/images/000631.png <config path> <checkpoint path> --out-file result.jpg`

### Reproduces the problem - error message

```
local loads checkpoint from path: /opt/ml/model/epoch_12.pth
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([16, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([16]).
/opt/conda/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:170: UserWarning: `Visualizer` backend is not initialized because save_dir is None.
  warnings.warn('`Visualizer` backend is not initialized '
Traceback (most recent call last):
  File "/opt/mmrotate/demo/image_demo.py", line 63, in <module>
    main(args)
  File "/opt/mmrotate/demo/image_demo.py", line 50, in main
    visualizer.add_datasample(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/dist/utils.py", line 346, in wrapper
    return func(*args, **kwargs)
  File "/opt/mmdetection/mmdet/visualization/local_visualizer.py", line 368, in add_datasample
    pred_img_data = self._draw_instances(image, pred_instances,
  File "/opt/mmrotate/mmrotate/visualization/local_visualizer.py", line 73, in _draw_instances
    polygons = bboxes.convert_to('qbox').tensor
AttributeError: 'Tensor' object has no attribute 'convert_to'
```

**Comment by jsago** [comment]
I encountered the same problem. Someone explained that mmrotate has rewritten the previous bbox writing method in order to access mmdet. It used to be a tensor, but now it continues to use the box list in mmdet. But I don't know how to solve it

**Comment by liuyanyi** [comment]
In 1.x, the model output should be RotatedBoxes, maybe in local_visualizer we should add a type check.

maybe you try replace this line to:
```
polygon = rbox2qbox(bboxes)
```

**Comment by austinmw** [comment]
@liuyanyi but I'm using 1.x and it seems to be type Tensor 🤔

**Comment by jsago** [comment]
@liuyanyi Thank you for your help. Yes, I did. But there are new problems here. I may need to understand them comprehensively
File "G:/Scientific_Research/mmrotate-1.0.0rc0/tools/my_test.py", line 130, in <module>
    main()
  File "G:/Scientific_Research/mmrotate-1.0.0rc0/tools/my_test.py", line 126, in main
    runner.test()
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1704, in test
    metrics = self.test_loop.run()  # type: ignore
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmengine\runner\loops.py", line 417, in run
    self.run_iter(idx, data_batch)
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmengine\runner\loops.py", line 438, in run_iter
    self.runner.call_hook(
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1720, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmdet\engine\hooks\visualization_hook.py", line 147, in after_test_iter
    self._visualizer.add_datasample(
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmengine\dist\utils.py", line 346, in wrapper
    return func(*args, **kwargs)
  File "D:\Software Area\Anaconda\envs\my_openmmlab\lib\site-packages\mmdet\visualization\local_visualizer.py", line 350, in add_datasample
    gt_img_data = self._draw_instances(image,
  File "G:\Scientific_Research\mmrotate-1.0.0rc0\mmrotate\visualization\local_visualizer.py", line 85, in _draw_instances
    positions = bboxes.centers + self.line_width
AttributeError: 'Tensor' object has no attribute 'centers'

**Comment by zytx121** [comment]
Hi @austinmw @jsago 
It is a bug. and you can replace 
https://github.com/open-mmlab/mmrotate/blob/766185ed317f99379cb14035a6f9e5cf8a5340ad/mmrotate/visualization/local_visualizer.py#L72
with
```
bboxes  = RotatedBoxes(bboxes)
polygons = bboxes.convert_to('qbox').tensor 
```
Because in 1.x, we use the `BoxType` to replace `Torch.Tensor`. We will provide detailed documentation about it later.

![image](https://user-images.githubusercontent.com/10410257/201500510-741410ae-e0b9-446c-89ab-9a0c0e085e94.png)

Now, you can refer unit test to learn how to use it.
https://github.com/open-mmlab/mmrotate/tree/dev-1.x/tests/test_structures/test_bbox

**Comment by austinmw** [comment]
Closing since this bug fixed, although when running demo I end up with a subsequent bug referenced in above merged PR

**Comment by Petros626** [comment]
@zytx121 @austinmw  which version (latest release or v1.0.0rc1) of  `MMRotate` is recommended to work with?
