### ISSUE TITLE
error:'MobileNet is not in the models registry'

### ISSUE THREAD

**Issue by ova2ova** [open-mmlab/mmrotate#628]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it wil
l remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lit
e and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: win32
Python: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.8
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31630 版
GCC: n/a
PyTorch: 1.9.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=c
OpenCV: 4.6.0
MMCV: 1.7.0
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: 10.2
MMRotate: 0.3.3+unknown

### Reproduces the problem - code sample

#mobilenet.py

import torch.nn as nn

from mmrotate.models.builder import ROTATED_BACKBONES

@ROTATED_BACKBONES.register_module()
class MobileNet(nn.Module):

    def __init__(self, arg1, arg2):
        pass

    def forward(self, x):  # should return a tuple
        pass

#dict

  backbone=dict(
        type='MobileNet'),

### Reproduces the problem - command or script

python tools/train.py H:\pythonproject\mmrotate-main\configs\rotated_faster_rcnn\rotated_faster_rcnn_r50_fpn_1x_dota_le90.py

### Reproduces the problem - error message

2022-11-17 16:29:49,149 - mmrotate - INFO - Set random seed to 1358332636, deterministic: False
Traceback (most recent call last):
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmrotate\models\detectors\rotate_faster_rcnn.py", line 22, in __init__
    super(RotatedFasterRCNN, self).__init__(
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmrotate\models\detectors\two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmrotate\models\builder.py", line 17, in build_backbone
    return ROTATED_BACKBONES.build(cfg)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\utils\registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'MobileNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 162, in main
    model = build_detector(
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmrotate\models\builder.py", line 55, in build_detector
    return ROTATED_DETECTORS.build(
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "H:\ProgramData\Anaconda3\envs\mmronate\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "RotatedFasterRCNN: 'MobileNet is not in the models registry'"

### Additional information

no

**Comment by nijkah** [comment]
Did you write the importing line as `from .mobilenet import MobileNet` in `mmrotate/models/backbones/__init__.py`?
All models should be imported for registration to access the line of `register_module()`.

**Comment by ova2ova** [comment]
> 

i do that，but the error is already existing

**Comment by nijkah** [comment]
Hmm, that's strange. Can I ask you to share your sample code on your github repository to reproduce the result?
