### ISSUE TITLE
你好，我在加载roi_trans_swin_tiny_fpn_1x_dota_le90-ddeee9ae.pth出现错误

### ISSUE THREAD

**Issue by jinshenrui1998** [open-mmlab/mmrotate#64]
2022-03-03 17:02:09,693 - mmrotate - INFO - Set random seed to 882269402, deterministic: False
/home/lsj/anaconda3/envs/JSRMMrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
2022-03-03 17:02:10,175 - mmdet - INFO - load checkpoint from local path: work_dirs/pretrain/roi_trans_swin_tiny_fpn_1x_dota_le90-ddeee9ae.pth
Traceback (most recent call last):
  File "/home/t4yp/jsr/mmrotate/tools/train.py", line 182, in <module>
    main()
  File "/home/t4yp/jsr/mmrotate/tools/train.py", line 156, in main
    model.init_weights()
  File "/home/lsj/anaconda3/envs/JSRMMrotate/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 116, in init_weights
    m.init_weights()
  File "/home/lsj/anaconda3/envs/JSRMMrotate/lib/python3.7/site-packages/mmdet/models/backbones/swin.py", line 727, in init_weights
    table_current = self.state_dict()[table_key]
KeyError: 'backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table'

在使用配置文件roi_trans_swin_tiny_fpn_1x_dota_le90.py和model_zoo提供的对应的预训练模型时出错。
修改成不用预训练模型时可以正常训练。

**Comment by zytx121** [comment]
Hi @jinshenrui1998 
Try to use  `load_from = work_dirs/pretrain/roi_trans_swin_tiny_fpn_1x_dota_le90-ddeee9ae.pth `
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/configs/_base_/default_runtime.py#L12

instead of `checkpoint = work_dirs/pretrain/roi_trans_swin_tiny_fpn_1x_dota_le90-ddeee9ae.pth `
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py#L23-L24

**Comment by jinshenrui1998** [comment]
问题解决了，谢谢

**Comment by zhangchi621** [comment]
> 问题解决了，谢谢

前辈 你好 请问你是怎么解决的
