### ISSUE TITLE
train mmrotate error- fail on evaluation due to device issue [Bug] 

### ISSUE THREAD

**Issue by naamagal** [open-mmlab/mmrotate#688]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

running on my own PC, with 1 GPU available.
I installed mmrotate on a new virtual environment mmrotate a few day ago.
(I used mmrotate before on a different venv)

### Reproduces the problem - code sample

I was running a train with a new config file (cfg) that uses the mmrotate object detection.

### Reproduces the problem - command or script

File ".../python3.8/site-packages/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)

### Reproduces the problem - error message

File ".../python3.8/site-packages/mmrotate/core/post_processing/bbox_nms_rotated.py", line 58, in multiclass_nms_rotated
bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
01/08/2023 11:26:18 - ERROR - torch.distributed.elastic.multiprocessing.api -   failed (exitcode: 1) local_rank: 0 (pid: 232863) of binary: /home/naama/Programs/venvs/auto_ml_venv/bin/python

**Comment by zytx121** [comment]
We don't support train on CPU environment. Please check whether your virtual environment can use GPU.

**Comment by yifanthomaswu** [comment]
> Hi @naamagal We don't support train on CPU environment. Please check whether your new virtual environment can use GPU.

I know you have been suggesting checking training environment and mmcv version to solve this problem but this is an actual compatibility issue of mmrotate with pytorch 1.13.

I have encountered the same issue and have narrowed down the cause to be pytorch version.

The environment below has no issue:
python: 3.8.15
pytorch: **1.12.1**
CUDA: 11.6
mmcv-full: 1.7.1
mmrotate: latest version (master)


The environment below has this issue:
python: 3.8.15
pytorch: **1.13.1**
CUDA: 11.6
mmcv-full: 1.7.1
mmrotate: latest version (master)

**Comment by zytx121** [comment]
Hi @yifanthomaswu! Thank you for your feedback, we will record it.

**Comment by Atlantisming** [comment]
I met the same problem when I run the demo script in the same environment as below:
python: 3.8.16
pytorch: 1.13.1
CUDA: 11.6
mmcv-full: 1.7.1
mmrotate: latest version (master)
`
(openmmlab) root@LAB_VM:~/mmrotate# python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
Traceback (most recent call last):
  File "demo/image_demo.py", line 45, in <module>
    main(args)
  File "demo/image_demo.py", line 32, in main
    result = inference_detector(model, args.img)
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 157, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/root/mmrotate/mmrotate/models/detectors/two_stage.py", line 183, in simple_test
    return self.roi_head.simple_test(
  File "/root/mmrotate/mmrotate/models/roi_heads/rotate_standard_roi_head.py", line 252, in simple_test
    det_bboxes, det_labels = self.simple_test_bboxes(
  File "/root/mmrotate/mmrotate/models/roi_heads/oriented_standard_roi_head.py", line 178, in simple_test_bboxes
    det_bbox, det_label = self.bbox_head.get_bboxes(
  File "/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
  File "/root/mmrotate/mmrotate/models/roi_heads/bbox_heads/rotated_bbox_head.py", line 418, in get_bboxes
    det_bboxes, det_labels = multiclass_nms_rotated(
  File "/root/mmrotate/mmrotate/core/post_processing/bbox_nms_rotated.py", line 58, in multiclass_nms_rotated
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
`

**Comment by rishabh10gpt** [comment]
Hello,
I did a work around to solve this issue, by modifying the file bbox_nms_rotated.py by :
replacing : labels = torch.arange(num_classes, dtype=torch.long)
with :  labels = torch.arange(num_classes, dtype=torch.long).to(scores.device)

**Comment by yangxue0827** [comment]
@zytx121 https://github.com/open-mmlab/mmrotate/issues/593

**Comment by Purple-Fusion** [comment]
> Hello,
> I did a work around to solve this issue, by modifying the file bbox_nms_rotated.py by :
> replacing : labels = torch.arange(num_classes, dtype=torch.long)
> with : labels = torch.arange(num_classes, dtype=torch.long).to(scores.device)

I tired this and it didn't work. Same error. How do I solve this.

**Comment by rishabh10gpt** [comment]
Can you show the exact error? and also the path of the py file which you have modified?
I believe the device related error would have been resolved as we are forcing all the variables to be on the same device.

**Comment by Purple-Fusion** [comment]
> 

I modified bbox_nms_rotated.py to look like this:
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from mmcv.ops import nms_rotated


def multiclass_nms_rotated(multi_bboxes,
                           multi_scores,
                           score_thr,
                           nms,
                           max_num=-1,
                           score_factors=None,
                           return_inds=False):
    """NMS for multi-class bboxes.

    Args:
        multi_bboxes (torch.Tensor): shape (n, #class*5) or (n, 5)
        multi_scores (torch.Tensor): shape (n, #class), where the last column
            contains scores of the background class, but this will be ignored.
        score_thr (float): bbox threshold, bboxes with scores lower than it
            will not be considered.
        nms (float): Config of NMS.
        max_num (int, optional): if there are more than max_num bboxes after
            NMS, only top max_num will be kept. Default to -1.
        score_factors (Tensor, optional): The factors multiplied to scores
            before applying NMS. Default to None.
        return_inds (bool, optional): Whether return the indices of kept
            bboxes. Default to False.

    Returns:
        tuple (dets, labels, indices (optional)): tensors of shape (k, 5), \
        (k), and (k). Dets are boxes with scores. Labels are 0-based.
    """
    num_classes = multi_scores.size(1) - 1
    # exclude background category
    if multi_bboxes.shape[1] > 5:
        bboxes = multi_bboxes.view(multi_scores.size(0), -1, 5)
    else:
        bboxes = multi_bboxes[:, None].expand(
            multi_scores.size(0), num_classes, 5)
    scores = multi_scores[:, :-1]

    labels = torch.arange(num_classes, dtype=torch.long).to(scores.device)
    labels = labels.view(1, -1).expand_as(scores)
    bboxes = bboxes.reshape(-1, 5)
    scores = scores.reshape(-1)
    labels = labels.reshape(-1)

    # remove low scoring boxes
    valid_mask = scores > score_thr
    if score_factors is not None:
        # expand the shape to match original shape of score
        score_factors = score_factors.view(-1, 1).expand(
            multi_scores.size(0), num_classes)
        score_factors = score_factors.reshape(-1)
        scores = scores * score_factors

    inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]

    if bboxes.numel() == 0:
        dets = torch.cat([bboxes, scores[:, None]], -1)
        if return_inds:
            return dets, labels, inds
        else:
            return dets, labels

    # Strictly, the maximum coordinates of the rotating box (x,y,w,h,a)
    # should be calculated by polygon coordinates.
    # But the conversion from rbbox to polygon will slow down the speed.
    # So we use max(x,y) + max(w,h) as max coordinate
    # which is larger than polygon max coordinate
    # max(x1, y1, x2, y2,x3, y3, x4, y4)
    max_coordinate = bboxes[:, :2].max() + bboxes[:, 2:4].max()
    offsets = labels.to(bboxes) * (max_coordinate + 1)
    if bboxes.size(-1) == 5:
        bboxes_for_nms = bboxes.clone()
        bboxes_for_nms[:, :2] = bboxes_for_nms[:, :2] + offsets[:, None]
    else:
        bboxes_for_nms = bboxes + offsets[:, None]
    _, keep = nms_rotated(bboxes_for_nms, scores, nms.iou_thr)

    if max_num > 0:
        keep = keep[:max_num]

    bboxes = bboxes[keep]
    scores = scores[keep]
    labels = labels[keep]

    if return_inds:
        return torch.cat([bboxes, scores[:, None]], 1), labels, keep
    else:
        return torch.cat([bboxes, scores[:, None]], 1), labels


def aug_multiclass_nms_rotated(merged_bboxes, merged_labels, score_thr, nms,
                               max_num, classes):
    """NMS for aug multi-class bboxes.

    Args:
        multi_bboxes (torch.Tensor): shape (n, #class*5) or (n, 5)
        multi_scores (torch.Tensor): shape (n, #class), where the last column
            contains scores of the background class, but this will be ignored.
        score_thr (float): bbox threshold, bboxes with scores lower than it
            will not be considered.
        nms (float): Config of NMS.
        max_num (int, optional): if there are more than max_num bboxes after
            NMS, only top max_num will be kept. Default to -1.
        classes (int): number of classes.

    Returns:
        tuple (dets, labels): tensors of shape (k, 5), and (k). Dets are boxes
            with scores. Labels are 0-based.
    """
    bboxes, labels = [], []

    for cls in range(classes):
        cls_bboxes = merged_bboxes[merged_labels == cls]
        inds = cls_bboxes[:, -1] > score_thr
        if len(inds) == 0:
            continue
        cur_bboxes = cls_bboxes[inds, :]
        cls_dets, _ = nms_rotated(cur_bboxes[:, :5], cur_bboxes[:, -1],
                                  nms.iou_thr)
        cls_labels = merged_bboxes.new_full((cls_dets.shape[0], ),
                                            cls,
                                            dtype=torch.long)
        if cls_dets.size()[0] == 0:
            continue
        bboxes.append(cls_dets)
        labels.append(cls_labels)

    if bboxes:
        bboxes = torch.cat(bboxes)
        labels = torch.cat(labels)
        if bboxes.shape[0] > max_num:
            _, _inds = bboxes[:, -1].sort(descending=True)
            _inds = _inds[:max_num]
            bboxes = bboxes[_inds]
            labels = labels[_inds]
    else:
        bboxes = merged_bboxes.new_zeros((0, merged_bboxes.size(-1)))
        labels = merged_bboxes.new_zeros((0, ), dtype=torch.long)

    return bboxes, labels
    
I changed what you said in an earlier comment.
I save the file but when i try to run through i get the same error message:
/usr/local/lib/python3.8/dist-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-68c4b67ac73d>](https://localhost:8080/#) in <module>
      1 # Use the detector to do inference
      2 img = 'demo/demo.jpg'
----> 3 result = inference_detector(model, img)

10 frames
[/usr/local/lib/python3.8/dist-packages/mmdet/apis/inference.py](https://localhost:8080/#) in inference_detector(model, imgs)
    155     # forward the model
    156     with torch.no_grad():
--> 157         results = model(return_loss=False, rescale=True, **data)
    158 
    159     if not is_batch:

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py](https://localhost:8080/#) in new_func(*args, **kwargs)
    117                                 f'method of those classes {supported_types}')
    118             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 119                 return old_func(*args, **kwargs)
    120 
    121             # get the arg spec of the decorated method

[/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py](https://localhost:8080/#) in forward(self, img, img_metas, return_loss, **kwargs)
    172             return self.forward_train(img, img_metas, **kwargs)
    173         else:
--> 174             return self.forward_test(img, img_metas, **kwargs)
    175 
    176     def _parse_losses(self, losses):

[/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py](https://localhost:8080/#) in forward_test(self, imgs, img_metas, **kwargs)
    145             if 'proposals' in kwargs:
    146                 kwargs['proposals'] = kwargs['proposals'][0]
--> 147             return self.simple_test(imgs[0], img_metas[0], **kwargs)
    148         else:
    149             assert imgs[0].size(0) == 1, 'aug test does not support ' \

[/content/mmrotate/mmrotate/models/detectors/two_stage.py](https://localhost:8080/#) in simple_test(self, img, img_metas, proposals, rescale)
    181             proposal_list = proposals
    182 
--> 183         return self.roi_head.simple_test(
    184             x, proposal_list, img_metas, rescale=rescale)
    185 

[/content/mmrotate/mmrotate/models/roi_heads/rotate_standard_roi_head.py](https://localhost:8080/#) in simple_test(self, x, proposal_list, img_metas, rescale)
    250         assert self.with_bbox, 'Bbox head must be implemented.'
    251 
--> 252         det_bboxes, det_labels = self.simple_test_bboxes(
    253             x, img_metas, proposal_list, self.test_cfg, rescale=rescale)
    254 

[/content/mmrotate/mmrotate/models/roi_heads/oriented_standard_roi_head.py](https://localhost:8080/#) in simple_test_bboxes(self, x, img_metas, proposals, rcnn_test_cfg, rescale)
    176         det_labels = []
    177         for i in range(len(proposals)):
--> 178             det_bbox, det_label = self.bbox_head.get_bboxes(
    179                 rois[i],
    180                 cls_score[i],

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py](https://localhost:8080/#) in new_func(*args, **kwargs)
    206                                 'method of nn.Module')
    207             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 208                 return old_func(*args, **kwargs)
    209             # get the arg spec of the decorated method
    210             args_info = getfullargspec(old_func)

[/content/mmrotate/mmrotate/models/roi_heads/bbox_heads/rotated_bbox_head.py](https://localhost:8080/#) in get_bboxes(self, rois, cls_score, bbox_pred, img_shape, scale_factor, rescale, cfg)
    416             return bboxes, scores
    417         else:
--> 418             det_bboxes, det_labels = multiclass_nms_rotated(
    419                 bboxes, scores, cfg.score_thr, cfg.nms, cfg.max_per_img)
    420             return det_bboxes, det_labels

[/content/mmrotate/mmrotate/core/post_processing/bbox_nms_rotated.py](https://localhost:8080/#) in multiclass_nms_rotated(multi_bboxes, multi_scores, score_thr, nms, max_num, score_factors, return_inds)
     56 
     57     inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
---> 58     bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
     59 
     60     if bboxes.numel() == 0:

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
I'm just trying to run the demo, I'm on google colab if that helps at all.

**Comment by rishabh10gpt** [comment]
[bbox_nms_rotated.txt](https://github.com/open-mmlab/mmrotate/files/10846763/bbox_nms_rotated.txt)
@Purple-Fusion Just try to replace that file with this file.
If it still doesn't work, try to add print statement to find on which device bboxes, scores and labels are on, and try to put all variables on the same device.

**Comment by Purple-Fusion** [comment]
> [bbox_nms_rotated.txt](https://github.com/open-mmlab/mmrotate/files/10846763/bbox_nms_rotated.txt) @Purple-Fusion Just try to replace that file with this file. If it still doesn't work, try to add print statement to find on which device bboxes, scores and labels are on, and try to put all variables on the same device.

This worked!! thankyou so much :)

**Comment by xiangguyoucai** [comment]
I had this problem before, and I solved it this way, and now I have this problem again, and I can't solve it this way.

> [bbox_nms_rotated.txt](https://github.com/open-mmlab/mmrotate/files/10846763/bbox_nms_rotated.txt) @Purple-Fusion只需尝试用这个文件替换那个文件。 如果还是不行，尝试添加打印语句来查找bboxes、scores和labels在哪个设备上，并尝试将所有变量放在同一个设备上。
