### ISSUE TITLE
[Bug] inference error: 'RotatedRTMDetSepBNHead is not in the model registry

### ISSUE THREAD

**Issue by yzbx** [open-mmlab/mmrotate#721]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla P4
CUDA_HOME: None
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0
OpenCV: 4.7.0
MMEngine: 0.5.0
MMRotate: 1.0.0rc1+

### Reproduces the problem - code sample

code from https://mmrotate.readthedocs.io/en/1.x/get_started.html

```
from mmdet.apis import init_detector, inference_detector
import mmrotate

config_file = 'oriented-rcnn-le90_r50_fpn_1x_dota.py'
checkpoint_file = 'oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
inference_detector(model, 'demo/demo.jpg')
```

I change the code for rtmdet_tiny
```
from mmdet.apis import inference_detector, init_detector
from mmdet.utils import register_all_modules as register_all_modules_mmdet

import mmrotate
from mmrotate.models.dense_heads import (RotatedRTMDetHead, RotatedRTMDetSepBNHead)
from mmrotate.registry import MODELS
from mmrotate.utils import register_all_modules

if __name__ == '__main__':
    print(MODELS)  # I find RotatedRTMDetSepBNHead in MODELS
    register_all_modules_mmdet(init_default_scope=False)
    register_all_modules(init_default_scope=False)
    config_file = 'configs/rotated_rtmdet/rotated_rtmdet_tiny-3x-dota.py'
    checkpoint_file = 'rotated_rtmdet_tiny-3x-dota-9d821076.pth'
    model = init_detector(config_file, checkpoint_file, device='cuda:0') # the init_detector will use the MODELS from mmdet, which cause error.
    inference_detector(model, 'demo/demo.jpg')
```

### Reproduces the problem - command or script

- after download the weight file from https://download.openmmlab.com/mmrotate/v1.0/rotated_rtmdet/rotated_rtmdet_tiny-3x-dota/rotated_rtmdet_tiny-3x-dota-9d821076.pth

```
python test_mmrotote.py
```

### Reproduces the problem - error message

```
Registry(name=model, items={'ReResNet': <class 'mmrotate.models.backbones.re_resnet.ReResNet'>, 'AngleBranchRetinaHead': <class 'mmrotate.models.dense_heads.angle_branch_retina_head.AngleBranchRetinaHead'>, 'RotatedRepPointsHead': <class 'mmrotate.models.dense_heads.rotated_reppoints_head.RotatedRepPointsHead'>, 'CFAHead': <class 
...
'mmrotate.models.dense_heads.rotated_atss_head.RotatedATSSHead'>, 'RotatedRTMDetHead': <class 
'mmrotate.models.dense_heads.rotated_rtmdet_head.RotatedRTMDetHead'>, 'RotatedRTMDetSepBNHead': <class 
'mmrotate.models.dense_heads.rotated_rtmdet_head.RotatedRTMDetSepBNHead'>, 'S2AHead': <class 
...
'mmrotate.models.roi_heads.roi_extractors.rotate_single_level_roi_extractor.RotatedSingleRoIExtractor'>})
02/07 06:30:37 - mmengine - WARNING - The "model" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/rtmdet.py", line 40, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 35, in __init__
    self.bbox_head = MODELS.build(bbox_head)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'RotatedRTMDetSepBNHead is not in the model registry. Please check whether the value of `RotatedRTMDetSepBNHead` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mmrotate.py", line 15, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/opt/conda/lib/python3.8/site-packages/mmdet/apis/inference.py", line 55, in init_detector
    model = MODELS.build(config.model)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `RTMDet` in mmdet/models/detectors/rtmdet.py: 'RotatedRTMDetSepBNHead is not in the model registry. Please check whether the value of `RotatedRTMDetSepBNHead` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"
```

### Additional information

```
I guess the MODELS in mmdet is different from mmrotate, which cause the problem.
```

**Comment by yzbx** [comment]
change to follow code, will fix the error, reference to `demo/image_demo.py`

```
from mmdet.apis import inference_detector, init_detector
from mmdet.utils import register_all_modules as register_all_modules_mmdet

import mmrotate
from mmrotate.models.dense_heads import (RotatedRTMDetHead, RotatedRTMDetSepBNHead)
from mmrotate.registry import MODELS
from mmrotate.utils import register_all_modules

if __name__ == '__main__':
    print(MODELS)
    # register_all_modules_mmdet(init_default_scope=False)
    register_all_modules(init_default_scope=True)
    config_file = 'configs/rotated_rtmdet/rotated_rtmdet_tiny-3x-dota.py'
    checkpoint_file = 'rotated_rtmdet_tiny-3x-dota-9d821076.pth'
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
    inference_detector(model, 'demo/demo.jpg')
```
