### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PANPEIWEN** [open-mmlab/mmrotate#738]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4: NVIDIA GeForce RTX 3090
GPU 5,6,7: NVIDIA A10
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.74
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.1+cu111
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMRotate: 0.3.4+

### Reproduces the problem - code sample

`        collector = defaultdict(list)
        for idx in range(len(self)):
            result = results[idx]
            img_id = self.img_ids[idx]
            splitname = img_id.split('__')
            oriname = splitname[0]
            pattern1 = re.compile(r'__\d+___\d+')
            x_y = re.findall(pattern1, img_id)
            x_y_2 = re.findall(r'\d+', x_y[0])
            x, y = int(x_y_2[0]), int(x_y_2[1])
            new_result = []
            for i, dets in enumerate(result):
                bboxes, scores = dets[:, :-1], dets[:, [-1]]
                ori_bboxes = bboxes.copy()
                ori_bboxes[..., :2] = ori_bboxes[..., :2] + np.array(
                    [x, y], dtype=np.float32)
                labels = np.zeros((bboxes.shape[0], 1)) + i
                new_result.append(
                    np.concatenate([labels, ori_bboxes, scores], axis=1))

            new_result = np.concatenate(new_result, axis=0)
            collector[oriname].append(new_result)`

### Reproduces the problem - command or script

python tools/test.py configs/rotated_fcos/rotated_fcos_sep_angle_r50_fpn_1x_dota_le90.py work_dirs/mAP76.50_rotated_fcos_sep_angle_r50_fpn_1x_dota_le90/epoch_65.pth --format-only

### Reproduces the problem - error message

Merging patch bboxes into full image!!!
Traceback (most recent call last):
  File "tools/test.py", line 263, in <module>
    main()
  File "tools/test.py", line 245, in main
    dataset.format_results(outputs, **kwargs)
  File "/data1/ppw/works/mmrotate/mmrotate/datasets/dota.py", line 325, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
  File "/data1/ppw/works/mmrotate/mmrotate/datasets/dota.py", line 228, in merge_det
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range

### Additional information

我希望能够将自己数据的的测试结果输出

**Comment by zytx121** [comment]
Hi @PANPEIWEN
Sorry, the output of other datasets is currently not supported. What format of test results do you need to output? We are considering supporting it in the next version.

**Comment by skywalker-ai** [comment]
Hi @zytx121 May I know what is the input data format the [merge_results](https://github.com/open-mmlab/mmrotate/blob/7755aa53b6e2d9c61fd765e67a60daa7ed8a1e05/mmrotate/core/patch/merge_results.py#L69)  expects? I am having trouble using this function.

**Comment by zytx121** [comment]
Hi @skywalker-ai, the input data format of merge_results is
https://github.com/open-mmlab/mmrotate/blob/7755aa53b6e2d9c61fd765e67a60daa7ed8a1e05/mmrotate/core/patch/merge_results.py#L69-L77
It is called in the following order: `huge_image_demo.py -> inference_detector_by_patches -> merge_results `.
The most important is the `inference_detector_by_patches` function.

**Comment by skywalker-ai** [comment]
@zytx121 Thank you, it worked.

**Comment by Nicolaing** [comment]
> @zytx121 Thank you, it worked.

how did you solved this?

**Comment by skywalker-ai** [comment]
@Nicolaing I was passing the data in wrong format, I had to change the format of the results before sending it into merge_results function
