### ISSUE TITLE
when i use DOTA datasets to train h2rbox_v2-le90_r50_fpn-1x_dota.py the following errors happen:RuntimeError  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 281, in loss_by_feat : expected scalar type long int but found float     pos_angle_targets[pos_agnostic_mask] = torch.where( RuntimeError: expected scalar type long int but found float     pos_angle_targets[pos_agnostic_mask] = torch.where( RuntimeError: expected scalar type long int but found float     pos_angle_targets[pos_agnostic_mask] = torch.where( RuntimeError: expected scalar type long int but found float[Bug] 

### ISSUE THREAD

**Issue by Czs99** [open-mmlab/mmrotate#826]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.7.0
MMEngine: 0.7.2
MMRotate: 1.0.0rc1+

### Reproduces the problem - code sample

bash ./tools/dist_train.sh ./configs/h2rbox_v2/h2rbox_v2-le90_r50_fpn-1x_dota.py 4

### Reproduces the problem - command or script

h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py line281
if self.rotation_agnostic_classes:
                pos_agnostic_mask = self._get_rotation_agnostic_mask(
                    pos_labels)
                pos_decoded_angle_preds[pos_agnostic_mask] = 0
                target_mask = torch.abs(
                    pos_angle_targets[pos_agnostic_mask]) < torch.pi / 4
                pos_angle_targets[pos_agnostic_mask] = torch.where(
                    target_mask, 0, -torch.pi / 2)

### Reproduces the problem - error message

04/21 09:34:07 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "optim_wrapper" registry tree. As a workaround, the current "optim_wrapper" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
04/21 09:34:14 - mmengine - INFO - load model from: torchvision://resnet50
04/21 09:34:14 - mmengine - INFO - Loads checkpoint by torchvision backend from path: torchvision://resnet50
04/21 09:34:14 - mmengine - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

04/21 09:34:14 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
04/21 09:34:14 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
04/21 09:34:14 - mmengine - INFO - Checkpoints will be saved to /remote-home/czs/h2rboxv2-mmrotate/work_dirs/h2rbox_v2-le90_r50_fpn-100epoch_RSDD.
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/h2rboxv2-mmrotate/mmrotate/structures/bbox/rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 122, in <module>
Traceback (most recent call last):
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 122, in <module>
Traceback (most recent call last):
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 122, in <module>
Traceback (most recent call last):
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 122, in <module>
    main()
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 118, in main
        main()    main()
main()

  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 118, in main
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 118, in main
  File "/remote-home/czs/h2rboxv2-mmrotate/./tools/train.py", line 118, in main
    runner.train()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1706, in train
    runner.train()
          File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1706, in train
runner.train()runner.train()

  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1706, in train
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    model = self.train_loop.run()  # type: ignore
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    model = self.train_loop.run()  # type: ignore
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    model = self.train_loop.run()  # type: ignore
      File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
self.run_epoch()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_epoch()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    self.run_epoch()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    self.run_iter(idx, data_batch)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    self.run_iter(idx, data_batch)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    outputs = self.runner.model.train_step(
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    outputs = self.runner.model.train_step(
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    losses = self._run_forward(data, mode='loss')
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    losses = self._run_forward(data, mode='loss')
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    results = self(**data, mode=mode)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    results = self(**data, mode=mode)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    output = self.module(*inputs[0], **kwargs[0])
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    output = self.module(*inputs[0], **kwargs[0])
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    output = self.module(*inputs[0], **kwargs[0])
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
      File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/detectors/h2rbox_v2.py", line 183, in loss
return forward_call(*input, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/detectors/h2rbox_v2.py", line 183, in loss
    return self.loss(inputs, data_samples)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/detectors/h2rbox_v2.py", line 183, in loss
    losses = self.bbox_head.loss(feat, batch_data_samples_all)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    return self.loss(inputs, data_samples)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/detectors/h2rbox_v2.py", line 183, in loss
        losses = self.bbox_head.loss(feat, batch_data_samples_all)losses = self.bbox_head.loss(feat, batch_data_samples_all)

  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 281, in loss_by_feat
    losses = self.bbox_head.loss(feat, batch_data_samples_all)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 281, in loss_by_feat
    losses = self.loss_by_feat(*loss_inputs)
  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 281, in loss_by_feat
    pos_angle_targets[pos_agnostic_mask] = torch.where(
    losses = self.loss_by_feat(*loss_inputs)
RuntimeError  File "/remote-home/czs/h2rboxv2-mmrotate/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 281, in loss_by_feat
: expected scalar type long int but found float
    pos_angle_targets[pos_agnostic_mask] = torch.where(
RuntimeError: expected scalar type long int but found float
    pos_angle_targets[pos_agnostic_mask] = torch.where(
RuntimeError: expected scalar type long int but found float
    pos_angle_targets[pos_agnostic_mask] = torch.where(
RuntimeError: expected scalar type long int but found float
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 714852) of binary: /remote-home/czs/anaconda3/envs/openmmlab1/bin/python
./tools/dist_train.sh: line 19: 714831 Segmentation fault      (core dumped) PYTHONPATH="$(dirname $0)/..":$PYTHONPATH python -m torch.distributed.launch --nnodes=$NNODES --node_rank=$NODE_RANK --master_addr=$MASTER_ADDR --nproc_per_node=$GPUS --master_port=$PORT $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}

### Additional information

I use the DOTA dataset

**Comment by yuyi1005** [comment]
Could you try it on PyTorch 1.13.1?

**Comment by Czs99** [comment]
> Some new features in PyTorch 1.13 is used in this code. Could you try it on PyTorch 1.13.1?

Thank you very very much! It works!

**Comment by yuyi1005** [comment]
The dataset is consistent with other rotated box supervised methods. We convert them to horizontal boxes in the training pipeline of H2RBox (see config file)

**Comment by yechao-prog** [comment]
Thank you very much
