### ISSUE TITLE
[Bug] a bug about data preprocess

### ISSUE THREAD

**Issue by lj-ij** [open-mmlab/mmrotate#835]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

ll rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.2
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu110
OpenCV: 4.1.2
MMCV: 1.7.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMRotate: 0.3.4+7755aa5

### Reproduces the problem - code sample

I have some problem with https://mmrotate.readthedocs.io/en/latest/tutorials/customize_config.html#. When tried to append the data preparation method such as RMosaic into my model. First I change the document in dotav1.py. and I also change the document in oriented_rcnn_r50_fpn_1x_dota_le90.py.But it was not worked and a bug was occured.Here is the document which has been changed.
In dotav1.py the following two line has been added into the train_pipeline
    **dict(type='RMosaic', img_size=(1024,1024)),
    dict(type='RRandomCrop'， crop_size=(1024,1024)),**
same change in in oriented_rcnn_r50_fpn_1x_dota_le90.py

### Reproduces the problem - command or script

python tools/train.py configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py --work-dir work-dir/run/oriented-rcnn/oriented_rcnn_r50_fpn_1x_dota_le90/

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 207, in _file2dict
    Config._validate_py_syntax(filename)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 105, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /data/liujin/mmrotate/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py: invalid character in identifier (<unknown>, line 138)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f2e521588b0>
Traceback (most recent call last):
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwi0w127t/tmp_ql3plzv.py'

### Additional information

The RMosaic  is expected to be added in the train process.What should I do, I has read the tutorial, but I can not understand it, thank you!

**Comment by lj-ij** [comment]
when I only append dict(type='RMosaic') to the document, a new bug occured.
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 181, in main
    train_detector(
  File "/data/liujin/mmrotate/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 220, in __getitem__
    data = self.prepare_train_img(idx)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 243, in prepare_train_img
    return self.pipeline(results)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/data/liujin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/pipelines/transforms.py", line 2042, in __call__
    results = self._mosaic_transform(results)
  File "/data/liujin/mmrotate/mmrotate/datasets/pipelines/transforms.py", line 469, in _mosaic_transform
    assert 'mix_results' in results
AssertionError

**Comment by zytx121** [comment]
Hi @lj-ij, please use [1.x](https://github.com/open-mmlab/mmrotate/tree/1.x) branch for using Mosaic. And you can refer to https://github.com/open-mmlab/mmrotate/blob/8b305251a05967f3cb88ad6322b8ed3742a5d56a/configs/rotated_rtmdet/rotated_rtmdet_l-100e-aug-dota.py#L82 for the detail.

**Comment by lj-ij** [comment]
> 

Thanks! is there any other way of data augmentation, such as mixup, can be used in mmrotate, I search it in the transformer.py, but found nothing.
