### ISSUE TITLE
List out of range when testing model on custom dataset [Bug] 

### ISSUE THREAD

**Issue by Nicolaing** [open-mmlab/mmrotate#838]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

Do you have any solution how to test a model on custom dataset with saved pth?

/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 2080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 2.0.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.0
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 11.3
MMCV CUDA Compiler: 11.7
MMRotate: 0.3.4+04405ab

### Reproduces the problem - code sample

import mmcv
from mmcv.runner import load_checkpoint

from mmdet.apis import inference_detector, show_result_pyplot
from mmrotate.models import build_detector

# Choose to use a config and initialize the detector
#config = 'oriented_rcnn_r50_fpn_1x_dota_le90.py'
config = '/home/nnguyen/bachelor_hands/config_model1.py'

# Setup a checkpoint file to load
# checkpoint = 'oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth'
checkpoint = '/home/nnguyen/bachelor_hands/hands_test_colab_copy/epoch_1.pth'
# checkpoint = '/home/nnguyen/bachelor_hands/hands_exps2/epoch_10.pth'

# Set the device to be used for evaluation
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Load the config
config = mmcv.Config.fromfile(config)
# Set pretrained to be None since we do not need pretrained model here
config.model.pretrained = None

# Initialize the detector
model = build_detector(config.model)

# Load checkpoint
checkpoint = load_checkpoint(model, checkpoint, map_location=device)

# Set the classes of models for inference
model.CLASSES = checkpoint['meta']['CLASSES']

# We need to set the model's cfg for inference
model.cfg = config

# Convert the model to GPU
model.to(device)
# Convert the model into evaluation mode
model.eval()

from mmrotate.datasets.builder import ROTATED_DATASETS
from mmrotate.datasets.dota import DOTADataset

@ROTATED_DATASETS.register_module()
class HandsDataset10k(DOTADataset):
    CLASSES = ('Wrist','Thump','Index_fingers','Middle_finger','Ring_finger','Pinky','Ring','Watch')

from mmcv import Config
cfg = Config.fromfile('/home/nnguyen/bachelor_hands/config_model1.py')

### **When I try to run a test on my saved config with my saved pth from the training:**
!python /home/nnguyen/bachelor_hands/mmrotate/tools/test.py   config_model1.py   /hands_exp_test/latest.pth --format-only --eval-options submission_dir=work_dirs/Task1_results

I get this error:

### Reproduces the problem - error message

[/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20): UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[/home/nnguyen/bachelor_hands/mmrotate/tools/test.py:123](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/tools/test.py:123): UserWarning: `mp_start_method` in `cfg` is set to `spawn` to use CUDA with multiprocessing when formatting output result.
  warnings.warn(
[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:38](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:38): UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:48](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:48): UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "[/home/nnguyen/bachelor_hands/mmrotate/tools/test.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/tools/test.py)", line 271, in <module>
    main()
  File "[/home/nnguyen/bachelor_hands/mmrotate/tools/test.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/tools/test.py)", line 207, in main
    dataset = build_dataset(cfg.data.test)
  File "[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/datasets/builder.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/datasets/builder.py)", line 47, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "[/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py)", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'HandsDataset10k is not in the dataset registry'

### I have also tried to train a model and then used the config on that model and try to test it with the new pth that i get after trying to test it, and i get another error:
_!python /home/nnguyen/bachelor_hands/mmrotate/tools/test.py /home/nnguyen/bachelor_hands/oriented_rcnn_r50_fpn_1x_dota_le90.py /home/nnguyen/bachelor_hands/new_dataset_logs/learning_rate/lr_05/latest.pth --eval=mAP_

[/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20): UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:38](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:38): UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:48](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/utils/setup_env.py:48): UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
[/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116): UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: [/home/nnguyen/bachelor_hands/new_dataset_logs/learning_rate/lr_05/latest.pth](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/new_dataset_logs/learning_rate/lr_05/latest.pth)
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([9, 1024]) from checkpoint, the shape in current model is torch.Size([16, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([16]).
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "[/home/nnguyen/bachelor_hands/mmrotate/tools/test.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/tools/test.py)", line 271, in <module>
    main()
  File "[/home/nnguyen/bachelor_hands/mmrotate/tools/test.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/tools/test.py)", line 263, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/datasets/dota.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/datasets/dota.py)", line 203, in evaluate
    mean_ap, _ = eval_rbbox_map(
  File "[/home/nnguyen/bachelor_hands/mmrotate/mmrotate/core/evaluation/eval_map.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22736475722d31342e73616e64626f782e74656b2e7364752e646b222c2275736572223a226e6e677579656e227d.vscode-resource.vscode-cdn.net/home/nnguyen/bachelor_hands/mmrotate/mmrotate/core/evaluation/eval_map.py)", line 169, in eval_rbbox_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range

**Comment by zytx121** [comment]
Hi @Nicolaing, please change the `num_classes` from 15 to 8, and train the model again.

**Comment by Shien11** [comment]
Hi @Nicolaing 
For the dataset registry, please reference to this https://github.com/open-mmlab/mmdetection/issues/1324#issuecomment-995143283, I suggest that you can revise in the original mmrotate/dataset/dota.py, and don't copy another.(some bugs I haven't fix yet too.)

The second question list index out of range, though I check the right num class, still pop this error.Though MMdetection don't suggest not doing evaluation, but I still skip it by chaning the model configs.
# evaluation = dict(interval=1, metric='mAP')
evaluation = dict(interval=30, metric='mAP') #my max epoch is 24 haha.
