### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheGreatTreatsby** [open-mmlab/mmrotate#847]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

ubuntu

### Reproduces the problem - code sample

    def _forward(self, batch_inputs: Tensor,
                 batch_data_samples: SampleList) -> tuple:
        """Network forward process. Usually includes backbone, neck and head
        forward without any post-processing.

        Args:
            batch_inputs (Tensor): Inputs with shape (N, C, H, W).
            batch_data_samples (list[:obj:`DetDataSample`]): Each item contains
                the meta information of each image and corresponding
                annotations.

        Returns:
            tuple: A tuple of features from ``rpn_head`` and ``roi_head``
            forward.
        """
        results = ()
        x = self.extract_feat(batch_inputs)

        if self.with_rpn:
            rpn_results_list = self.rpn_head.predict(
                x, batch_data_samples, rescale=False)
        else:
            assert batch_data_samples[0].get('proposals', None) is not None
            rpn_results_list = [
                data_sample.proposals for data_sample in batch_data_samples
            ]
        roi_outs = self.roi_head.forward(x, rpn_results_list,
                                         batch_data_samples)
        results = results + (roi_outs, )
        return results

### Reproduces the problem - command or script

mmrotate/tools/analysis_tools/get_flops.py
site-packages/mmdet/models/detectors/two_stage.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/mmrotate/tools/analysis_tools/get_flops.py", line 91, in <module>
    main()
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/mmrotate/tools/analysis_tools/get_flops.py", line 76, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 107, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/liusir/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 97, in forward
    return self._forward(inputs, data_samples)
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 134, in _forward
    rpn_results_list = self.rpn_head.predict(
  File "/home/liusir/PycharmProjects/pythonProject/mmrotatex/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 193, in predict
    batch_img_metas = [
TypeError: 'NoneType' object is not iterable

### Additional information

two-stage models cannot get the flops in 1.x，but one stage models can！

**Comment by zytx121** [comment]
@TheGreatTreatsby, since operators such as RotatedRoIAlign do not support calculating FLOPS, FLOPS cannot be calculated in the two-stage detectors.
