### ISSUE TITLE
[Bug] An issue when i try to generate confusion_matrix

### ISSUE THREAD

**Issue by flyweifly** [open-mmlab/mmrotate#869]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

System environment:
    sys.platform: linux
    Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 1406225927
    GPU 0,1,2,3: NVIDIA GeForce RTX 4090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.2, V11.2.152
    GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
    PyTorch: 1.8.0+cu111
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.9.0+cu111
    OpenCV: 4.7.0
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

### Reproduces the problem - code sample

assert mode in ['iou', 'iof']
# Either the boxes are empty or the length of boxes's last dimension is 5
assert (bboxes1.size(-1) == 5 or bboxes1.size(0) == 0)
assert (bboxes2.size(-1) == 5 or bboxes2.size(0) == 0)

### Reproduces the problem - command or script

python tools/analysis_tools/confusion_matrix.py configs/rotated_rtmdet/rotated_rtmdet_l-coco_pretrain-3x-dota_ms.py ./results_95s.pkl ./confusion_matrix

### Reproduces the problem - error message

[                                                  ] 0/1100, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/analysis_tools/confusion_matrix.py", line 266, in <module>
    main()
  File "tools/analysis_tools/confusion_matrix.py", line 253, in main
    confusion_matrix = calculate_confusion_matrix(dataset, results,
  File "tools/analysis_tools/confusion_matrix.py", line 87, in calculate_confusion_matrix
    analyze_per_img_dets(confusion_matrix, gts, res_bboxes, score_thr,
  File "tools/analysis_tools/confusion_matrix.py", line 135, in analyze_per_img_dets
    ious = rbbox_overlaps(det_bboxes[:, :5], gt_bboxes)
  File "/home/featurize/work/mmrotate-1.0.0rc1/mmrotate/structures/bbox/bbox_overlaps.py", line 29, in rbbox_overlaps
    assert (bboxes1.size(-1) == 5 or bboxes1.size(0) == 0)
TypeError: 'int' object is not callable

**Comment by flyweifly** [comment]
thank you for your work, but another problem occured...

[                                                  ] 0/800, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/analysis_tools/confusion_matrix.py", line 275, in <module>
    main()
  File "tools/analysis_tools/confusion_matrix.py", line 262, in main
    confusion_matrix = calculate_confusion_matrix(dataset, results,
  File "tools/analysis_tools/confusion_matrix.py", line 88, in calculate_confusion_matrix
    analyze_per_img_dets(confusion_matrix, gts, res_bboxes, score_thr,
  File "tools/analysis_tools/confusion_matrix.py", line 128, in analyze_per_img_dets
    gt_bboxes = qbox2rbox(gt_bboxes)
  File "/home/featurize/work/mmrotate-1.0.0rc1/mmrotate/structures/bbox/box_converters.py", line 112, in qbox2rbox
    (x, y), (w, h), angle = cv2.minAreaRect(pts)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

**Comment by flyweifly** [comment]
The version of my mmrotate is 1.0.0rc1

**Comment by liuyanyi** [comment]
> thank you for your work, but another problem occured...
> 
> [ ] 0/800, elapsed: 0s, ETA:Traceback (most recent call last): File "tools/analysis_tools/confusion_matrix.py", line 275, in main() File "tools/analysis_tools/confusion_matrix.py", line 262, in main confusion_matrix = calculate_confusion_matrix(dataset, results, File "tools/analysis_tools/confusion_matrix.py", line 88, in calculate_confusion_matrix analyze_per_img_dets(confusion_matrix, gts, res_bboxes, score_thr, File "tools/analysis_tools/confusion_matrix.py", line 128, in analyze_per_img_dets gt_bboxes = qbox2rbox(gt_bboxes) File "/home/featurize/work/mmrotate-1.0.0rc1/mmrotate/structures/bbox/box_converters.py", line 112, in qbox2rbox (x, y), (w, h), angle = cv2.minAreaRect(pts) cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

In my environment it works fine. What's your opencv version, my version is 
```
opencv-python                 4.7.0.72
```

you can add a `.float()` at the input of the `qbox2rbox`, this may work, but im not sure.

**Comment by flyweifly** [comment]
thank you, it works

**Comment by notbug1024** [comment]
Hello, when I used a data set in dota format to experiment with rotating frames, I encountered the same problem as the original poster @flymmmfly , and I solved it according to the method provided below @liuyanyi.

However, when I experimented with the coco format data set, an error still occurred. The specific error information is as follows. How should I solve it? 

  File "/mnt/chen2t/mmrotate-1.0.0rc1/tools/analysis_tools/confusion_matrix_modify.py", line 276, in <module>
    main()
  File "/mnt/chen2t/mmrotate-1.0.0rc1/tools/analysis_tools/confusion_matrix_modify.py", line 263, in main
    confusion_matrix = calculate_confusion_matrix(dataset, results,
  File "/mnt/chen2t/mmrotate-1.0.0rc1/tools/analysis_tools/confusion_matrix_modify.py", line 88, in calculate_confusion_matrix
    analyze_per_img_dets(confusion_matrix, gts, res_bboxes, score_thr,
  File "/mnt/chen2t/mmrotate-1.0.0rc1/tools/analysis_tools/confusion_matrix_modify.py", line 129, in analyze_per_img_dets
    gt_bboxes = qbox2rbox(gt_bboxes)
  File "/mnt/chen2t/mmrotate-1.0.0rc1/mmrotate/structures/bbox/box_converters.py", line 109, in qbox2rbox
    points = boxes.cpu().numpy().reshape(-1, 4, 2)
ValueError: cannot reshape array of size 4 into shape (4,2)
