### ISSUE TITLE
[Bug] IndexError: list index out of range

### ISSUE THREAD

**Issue by Doby6** [open-mmlab/mmrotate#880]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: win32
Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4080
CUDA_HOME: D:\CUDA\ProgramFiles\NVIDIA GPU computing toolkit\CUDA\v11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版
GCC: n/a
PyTorch: 1.10.2+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3+cu113
OpenCV: 4.7.0
MMEngine: 0.7.4
MMRotate: 1.0.0rc1+unknown

### Reproduces the problem - code sample

rotated_rtmdet_s-3x-dota.py or mmrotate-dev-1.x\mmrotate\datasets\dota.py

### Reproduces the problem - command or script

python tools/train.py configs/rotated_rtmdet/rotated_rtmdet_s-3x-dota.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "d:\suanfa\mmrotate\mmrotate-dev-1.x\mmrotate\datasets\dota.py", line 49, in __init__
    super().__init__(**kwargs)
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\dataset\base_dataset.py", line 245, in __init__
    self.full_init()
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\dataset\base_dataset.py", line 296, in full_init
    self.data_list = self.load_data_list()
  File "d:\suanfa\mmrotate\mmrotate-dev-1.x\mmrotate\datasets\dota.py", line 97, in load_data_list
    cls_name = bbox_info[8]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\runner\loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\runner\runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
IndexError: class `DOTADataset` in mmrotate/datasets/dota.py: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    runner.train()
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\runner\runner.py", line 1687, in train
    self._train_loop = self.build_train_loop(
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\runner\runner.py", line 1479, in build_train_loop
    loop = LOOPS.build(
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
IndexError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `DOTADataset` in mmrotate/datasets/dota.py: list index out of range

### Additional information

Could this be a problem with my data set or an environment problem?

**Comment by jsxyhelu** [comment]
dota是15类，如果你训练其它数据（比如fair1m是37类）需要在配置文件中进行修改

**Comment by Doby6** [comment]
> dota是15类，如果你训练其它数据（比如fair1m是37类）需要在配置文件中进行修改

你好，十分感谢你的回答，但能告诉我一下具体改哪个配置文件吗，是dota.py这个吗

**Comment by GuiBao306** [comment]
你好，那训练HRSC2016数据集是多少类呀，IndexError:tuple index out of range我总是报这个错误是为什么呢？

> dota是15类，如果你训练其它数据（比如fair1m是37类）需要在配置文件中进行修改
