### ISSUE TITLE
How to transform the model train in 1.x branch into dev-1.x?[Docs] 

### ISSUE THREAD

**Issue by LLsmile** [open-mmlab/mmrotate#895]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

The branch is confusing. And I trained a rotated-rtmdet in `1.x` branch. The model can be converted into onnx in cpu mode but failed in gpu mode. I'm not sure it's the problem of mmdeploy or just related with different branch? Following is the error info:
Traceback (most recent call last):
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/mmrotate-1.x/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/mmrotate-1.x/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/mmrotate-1.x/mmdeploy/mmdeploy/codebase/base/task.py", line 123, in build_pytorch_model
    load_checkpoint(model, model_checkpoint, map_location=self.device)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 1052, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/xyz/anaconda3/envs/deploy/lib/python3.7/site-packages/torch/serialization.py", line 220, in default_restore_location
    + location + ")")
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)
07/04 11:04:04 - mmengine - ERROR - /home/xyz/workspace/06_study_materials/02_model/01_detection/mmrotate-1.x/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Comment by TekayaNidham** [comment]
which mmdeploy version have you used? according to their documentation, you have to use mmdeploy 0.x.y in order to work with mmrotate

**Comment by TekayaNidham** [comment]
according to your error log, looks like you're using 1.x, try switching to 0.x

**Comment by LLsmile** [comment]
mmdeploy is latest `dev-1.x` branch. And it only failed in gpu mode.
