### ISSUE TITLE
2560 x 1920的彩色图片使用rtmdet模型训练运行报错

### ISSUE THREAD

**Issue by kc-w** [open-mmlab/mmrotate#912]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: win32
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.109
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30147 版
GCC: n/a
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.5.3
MMEngine: 0.8.4
MMRotate: 1.0.0rc1+

### Reproduces the problem - code sample

![image](https://github.com/open-mmlab/mmrotate/assets/39193398/08c4704f-9730-4bb8-8ee0-50a517ec3ff3)

### Reproduces the problem - command or script

train.py

### Reproduces the problem - error message

E:\projectTest\mmrotate\mmrotate\structures\bbox\rotated_boxes.py:192: UserWarning: The `clip` function does nothing in `RotatedBoxes`.
  warnings.warn('The `clip` function does nothing in `RotatedBoxes`.')
D:\Python\Python39\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
08/09 10:16:52 - mmengine - INFO - Epoch(train)  [1][ 1/82]  base_lr: 2.5000e-09 lr: 2.5000e-09  eta: 6:04:55  time: 7.4198  data_time: 3.3818  memory: 5293  loss: 1.0186  loss_cls: 1.0166  loss_bbox: 0.0020
08/09 10:16:52 - mmengine - INFO - Epoch(train)  [1][ 2/82]  base_lr: 2.5275e-07 lr: 2.5275e-07  eta: 3:11:29  time: 3.8949  data_time: 1.6934  memory: 5397  loss: 1.1217  loss_cls: 1.1204  loss_bbox: 0.0013
08/09 10:16:52 - mmengine - INFO - Epoch(train)  [1][ 3/82]  base_lr: 5.0300e-07 lr: 5.0300e-07  eta: 2:14:19  time: 2.7329  data_time: 1.1433  memory: 5398  loss: 0.9446  loss_cls: 0.9434  loss_bbox: 0.0012
08/09 10:16:53 - mmengine - INFO - Epoch(train)  [1][ 4/82]  base_lr: 7.5324e-07 lr: 7.5324e-07  eta: 1:45:18  time: 2.1432  data_time: 0.8607  memory: 5397  loss: 0.9639  loss_cls: 0.9627  loss_bbox: 0.0012
08/09 10:16:53 - mmengine - INFO - Epoch(train)  [1][ 5/82]  base_lr: 1.0035e-06 lr: 1.0035e-06  eta: 1:27:52  time: 1.7889  data_time: 0.6906  memory: 5397  loss: 0.9004  loss_cls: 0.8976  loss_bbox: 0.0028
08/09 10:16:53 - mmengine - INFO - Epoch(train)  [1][ 6/82]  base_lr: 1.2537e-06 lr: 1.2537e-06  eta: 1:16:15  time: 1.5530  data_time: 0.5775  memory: 5397  loss: 0.8497  loss_cls: 0.8473  loss_bbox: 0.0024
08/09 10:16:54 - mmengine - INFO - Epoch(train)  [1][ 7/82]  base_lr: 1.5040e-06 lr: 1.5040e-06  eta: 1:07:56  time: 1.3843  data_time: 0.4963  memory: 5397  loss: 0.7880  loss_cls: 0.7858  loss_bbox: 0.0021
08/09 10:16:54 - mmengine - INFO - Epoch(train)  [1][ 8/82]  base_lr: 1.7542e-06 lr: 1.7542e-06  eta: 1:01:42  time: 1.2577  data_time: 0.4355  memory: 5397  loss: 0.7673  loss_cls: 0.7654  loss_bbox: 0.0020
08/09 10:16:55 - mmengine - INFO - Epoch(train)  [1][ 9/82]  base_lr: 2.0045e-06 lr: 2.0045e-06  eta: 0:56:54  time: 1.1604  data_time: 0.3882  memory: 5398  loss: 0.7619  loss_cls: 0.7599  loss_bbox: 0.0020
08/09 10:16:55 - mmengine - INFO - Epoch(train)  [1][10/82]  base_lr: 2.2547e-06 lr: 2.2547e-06  eta: 0:53:04  time: 1.0824  data_time: 0.3512  memory: 5398  loss: 0.7333  loss_cls: 0.7310  loss_bbox: 0.0022
08/09 10:16:55 - mmengine - INFO - Epoch(train)  [1][11/82]  base_lr: 2.5050e-06 lr: 2.5050e-06  eta: 0:49:53  time: 1.0177  data_time: 0.3201  memory: 5397  loss: 0.6919  loss_cls: 0.6899  loss_bbox: 0.0020
08/09 10:16:56 - mmengine - INFO - Epoch(train)  [1][12/82]  base_lr: 2.7552e-06 lr: 2.7552e-06  eta: 0:47:13  time: 0.9639  data_time: 0.2943  memory: 5397  loss: 0.6634  loss_cls: 0.6612  loss_bbox: 0.0022
08/09 10:16:56 - mmengine - INFO - Epoch(train)  [1][13/82]  base_lr: 3.0055e-06 lr: 3.0055e-06  eta: 0:45:03  time: 0.9197  data_time: 0.2732  memory: 5397  loss: 0.6348  loss_cls: 0.6327  loss_bbox: 0.0021
08/09 10:16:56 - mmengine - INFO - Epoch(train)  [1][14/82]  base_lr: 3.2557e-06 lr: 3.2557e-06  eta: 0:43:07  time: 0.8806  data_time: 0.2544  memory: 5398  loss: 0.6105  loss_cls: 0.6085  loss_bbox: 0.0020
08/09 10:16:57 - mmengine - INFO - Epoch(train)  [1][15/82]  base_lr: 3.5060e-06 lr: 3.5060e-06  eta: 0:41:26  time: 0.8467  data_time: 0.2381  memory: 5397  loss: 0.5868  loss_cls: 0.5849  loss_bbox: 0.0019
08/09 10:16:57 - mmengine - INFO - Epoch(train)  [1][16/82]  base_lr: 3.7562e-06 lr: 3.7562e-06  eta: 0:39:59  time: 0.8173  data_time: 0.2238  memory: 5398  loss: 0.5664  loss_cls: 0.5645  loss_bbox: 0.0019
08/09 10:16:58 - mmengine - INFO - Epoch(train)  [1][17/82]  base_lr: 4.0065e-06 lr: 4.0065e-06  eta: 0:38:42  time: 0.7914  data_time: 0.2114  memory: 5398  loss: 0.5477  loss_cls: 0.5456  loss_bbox: 0.0021
08/09 10:16:58 - mmengine - INFO - Epoch(train)  [1][18/82]  base_lr: 4.2567e-06 lr: 4.2567e-06  eta: 0:37:33  time: 0.7680  data_time: 0.2002  memory: 5397  loss: 0.5311  loss_cls: 0.5292  loss_bbox: 0.0020
08/09 10:16:58 - mmengine - INFO - Epoch(train)  [1][19/82]  base_lr: 4.5070e-06 lr: 4.5070e-06  eta: 0:36:31  time: 0.7472  data_time: 0.1902  memory: 5397  loss: 0.5159  loss_cls: 0.5140  loss_bbox: 0.0019
08/09 10:16:59 - mmengine - INFO - Epoch(train)  [1][20/82]  base_lr: 4.7572e-06 lr: 4.7572e-06  eta: 0:35:35  time: 0.7284  data_time: 0.1812  memory: 5397  loss: 0.5015  loss_cls: 0.4996  loss_bbox: 0.0019
08/09 10:16:59 - mmengine - INFO - Epoch(train)  [1][21/82]  base_lr: 5.0075e-06 lr: 5.0075e-06  eta: 0:34:46  time: 0.7118  data_time: 0.1730  memory: 5398  loss: 0.4884  loss_cls: 0.4864  loss_bbox: 0.0020
08/09 10:16:59 - mmengine - INFO - Epoch(train)  [1][22/82]  base_lr: 5.2577e-06 lr: 5.2577e-06  eta: 0:34:00  time: 0.6963  data_time: 0.1656  memory: 5397  loss: 0.4763  loss_cls: 0.4744  loss_bbox: 0.0020
08/09 10:17:00 - mmengine - INFO - Epoch(train)  [1][23/82]  base_lr: 5.5080e-06 lr: 5.5080e-06  eta: 0:33:18  time: 0.6822  data_time: 0.1588  memory: 5397  loss: 0.4654  loss_cls: 0.4635  loss_bbox: 0.0019
08/09 10:17:00 - mmengine - INFO - Epoch(train)  [1][24/82]  base_lr: 5.7582e-06 lr: 5.7582e-06  eta: 0:32:39  time: 0.6693  data_time: 0.1526  memory: 5397  loss: 0.4553  loss_cls: 0.4534  loss_bbox: 0.0019
08/09 10:17:01 - mmengine - INFO - Epoch(train)  [1][25/82]  base_lr: 6.0084e-06 lr: 6.0084e-06  eta: 0:32:04  time: 0.6574  data_time: 0.1470  memory: 5397  loss: 0.4460  loss_cls: 0.4441  loss_bbox: 0.0019
08/09 10:17:01 - mmengine - INFO - Epoch(train)  [1][26/82]  base_lr: 6.2587e-06 lr: 6.2587e-06  eta: 0:31:32  time: 0.6466  data_time: 0.1418  memory: 5397  loss: 0.4374  loss_cls: 0.4355  loss_bbox: 0.0019
08/09 10:17:01 - mmengine - INFO - Epoch(train)  [1][27/82]  base_lr: 6.5089e-06 lr: 6.5089e-06  eta: 0:31:01  time: 0.6365  data_time: 0.1369  memory: 5397  loss: 0.4293  loss_cls: 0.4274  loss_bbox: 0.0019
08/09 10:17:02 - mmengine - INFO - Epoch(train)  [1][28/82]  base_lr: 6.7592e-06 lr: 6.7592e-06  eta: 0:30:33  time: 0.6271  data_time: 0.1324  memory: 5397  loss: 0.4219  loss_cls: 0.4200  loss_bbox: 0.0019
08/09 10:17:02 - mmengine - INFO - Epoch(train)  [1][29/82]  base_lr: 7.0094e-06 lr: 7.0094e-06  eta: 0:30:07  time: 0.6184  data_time: 0.1282  memory: 5397  loss: 0.4149  loss_cls: 0.4130  loss_bbox: 0.0019
08/09 10:17:02 - mmengine - INFO - Epoch(train)  [1][30/82]  base_lr: 7.2597e-06 lr: 7.2597e-06  eta: 0:29:44  time: 0.6105  data_time: 0.1243  memory: 5397  loss: 0.4087  loss_cls: 0.4064  loss_bbox: 0.0023
08/09 10:17:03 - mmengine - INFO - Epoch(train)  [1][31/82]  base_lr: 7.5099e-06 lr: 7.5099e-06  eta: 0:29:22  time: 0.6033  data_time: 0.1210  memory: 5398  loss: 0.4026  loss_cls: 0.4002  loss_bbox: 0.0024
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:276: block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "E:\projectTest\mmrotate\tools\train.py", line 249, in <module>
    main()
  File "E:\projectTest\mmrotate\tools\train.py", line 245, in main
    runner.train()
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "D:\Python\Python39\lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "D:\Python\Python39\lib\site-packages\mmengine\model\base_model\base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\detectors\base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\detectors\single_stage.py", line 78, in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\dense_heads\base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "E:\projectTest\mmrotate\mmrotate\models\dense_heads\rotated_rtmdet_head.py", line 299, in loss_by_feat
    cls_reg_targets = self.get_targets(
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\dense_heads\rtmdet_head.py", line 356, in get_targets
    all_assign_metrics, sampling_results_list) = multi_apply(
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\utils\misc.py", line 219, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "E:\projectTest\mmrotate\mmrotate\models\dense_heads\rotated_rtmdet_head.py", line 395, in _get_targets_single
    assign_result = self.assigner.assign(pred_instances, gt_instances,
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\task_modules\assigners\dynamic_soft_label_assigner.py", line 172, in assign
    matched_pred_ious, matched_gt_inds = self.dynamic_k_matching(
  File "e:\projecttest\mmdetection-3.0.0\mmdet\models\task_modules\assigners\dynamic_soft_label_assigner.py", line 208, in dynamic_k_matching
    _, pos_idx = torch.topk(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Process finished with exit code 1

### Additional information

angle_version = 'le90'
base_lr = 0.00025
checkpoint = 'E:/DLTrainKit/DeepLearningTrain/train/mmrotate/configs/rtmdet_s_ms.pth'
custom_hooks = [
    dict(type='mmdet.NumClassCheckHook'),
    dict(
        ema_type='mmdet.ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
]
data_root = 'E:/projectTest/yolov5_obb/VOCData/'
dataset_type = 'DOTADataset'
default_hooks = dict(
    checkpoint=dict(interval=12, max_keep_ckpts=3, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='mmdet.DetVisualizationHook'))
default_scope = 'mmrotate'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
file_client_args = dict(backend='disk')
interval = 12
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
max_epochs = 36
model = dict(
    backbone=dict(
        act_cfg=dict(type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=0.33,
        expand_ratio=0.5,
        init_cfg=dict(
            checkpoint=
            'E:/DLTrainKit/DeepLearningTrain/train/mmrotate/configs/rtmdet_s_ms.pth',
            prefix='backbone.',
            type='Pretrained'),
        norm_cfg=dict(type='BN'),
        type='mmdet.CSPNeXt',
        widen_factor=0.5),
    bbox_head=dict(
        act_cfg=dict(type='SiLU'),
        anchor_generator=dict(
            offset=0, strides=[
                8,
                16,
                32,
            ], type='mmdet.MlvlPointGenerator'),
        angle_version='le90',
        bbox_coder=dict(angle_version='le90', type='DistanceAnglePointCoder'),
        exp_on_reg=False,
        feat_channels=128,
        in_channels=128,
        loss_angle=None,
        loss_bbox=dict(loss_weight=2.0, mode='linear', type='RotatedIoULoss'),
        loss_cls=dict(
            beta=2.0,
            loss_weight=1.0,
            type='mmdet.QualityFocalLoss',
            use_sigmoid=True),
        norm_cfg=dict(type='BN'),
        num_classes=2,
        pred_kernel_size=1,
        scale_angle=False,
        share_conv=True,
        stacked_convs=2,
        type='RotatedRTMDetSepBNHead',
        use_hbbox_loss=False,
        with_objectness=False),
    data_preprocessor=dict(
        batch_augments=None,
        bgr_to_rgb=False,
        boxtype2tensor=False,
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            57.375,
            57.12,
            58.395,
        ],
        type='mmdet.DetDataPreprocessor'),
    neck=dict(
        act_cfg=dict(type='SiLU'),
        expand_ratio=0.5,
        in_channels=[
            128,
            256,
            512,
        ],
        norm_cfg=dict(type='BN'),
        num_csp_blocks=1,
        out_channels=128,
        type='mmdet.CSPNeXtPAFPN'),
    test_cfg=dict(
        max_per_img=2000,
        min_bbox_size=0,
        nms=dict(iou_threshold=0.1, type='nms_rotated'),
        nms_pre=2000,
        score_thr=0.05),
    train_cfg=dict(
        allowed_border=-1,
        assigner=dict(
            iou_calculator=dict(type='RBboxOverlaps2D'),
            topk=13,
            type='mmdet.DynamicSoftLabelAssigner'),
        debug=False,
        pos_weight=-1),
    type='mmdet.RTMDet')
optim_wrapper = dict(
    optimizer=dict(lr=0.00025, type='AdamW', weight_decay=0.05),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=1e-05,
        type='LinearLR'),
    dict(
        T_max=18,
        begin=18,
        by_epoch=True,
        convert_to_iter_based=True,
        end=36,
        eta_min=1.25e-05,
        type='CosineAnnealingLR'),
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='labelTxt/val/',
        data_prefix=dict(img_path='images/val/'),
        data_root=data_root,
        img_shape=(
            2560,
            1920,
        ),
        pipeline=[
            dict(
                file_client_args=dict(backend='disk'),
                type='mmdet.LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                2560,
                1920,
            ), type='mmdet.Resize'),
            dict(
                box_type='qbox', type='mmdet.LoadAnnotations', with_bbox=True),
            dict(
                box_type_mapping=dict(gt_bboxes='rbox'),
                type='ConvertBoxType'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    2560,
                    1920,
                ),
                type='mmdet.Pad'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='mmdet.PackDetInputs'),
        ],
        test_mode=True,
        type='DOTADataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(metric='mAP', type='DOTAMetric')
test_pipeline = [
    dict(
        file_client_args=dict(backend='disk'), type='mmdet.LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        2560,
        1920,
    ), type='mmdet.Resize'),
    dict(
        pad_val=dict(img=(
            114,
            114,
            114,
        )),
        size=(
            2560,
            1920,
        ),
        type='mmdet.Pad'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='mmdet.PackDetInputs'),
]
train_cfg = dict(max_epochs=36, type='EpochBasedTrainLoop', val_interval=12)
train_dataloader = dict(
    batch_sampler=None,
    batch_size=1,
    dataset=dict(
        ann_file='labelTxt/train/',
        data_prefix=dict(img_path='images/train/'),
        data_root=data_root,
        filter_cfg=dict(filter_empty_gt=True),
        img_shape=(
            2560,
            1920,
        ),
        pipeline=[
            dict(
                file_client_args=dict(backend='disk'),
                type='mmdet.LoadImageFromFile'),
            dict(
                box_type='qbox', type='mmdet.LoadAnnotations', with_bbox=True),
            dict(
                box_type_mapping=dict(gt_bboxes='rbox'),
                type='ConvertBoxType'),
            dict(keep_ratio=True, scale=(
                2560,
                1920,
            ), type='mmdet.Resize'),
            dict(
                direction=[
                    'horizontal',
                    'vertical',
                    'diagonal',
                ],
                prob=0.75,
                type='mmdet.RandomFlip'),
            dict(
                angle_range=180,
                prob=0.5,
                rect_obj_labels=[
                    9,
                    11,
                ],
                type='RandomRotate'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    2560,
                    1920,
                ),
                type='mmdet.Pad'),
            dict(type='mmdet.PackDetInputs'),
        ],
        type='DOTADataset'),
    num_workers=1,
    persistent_workers=True,
    pin_memory=False,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        file_client_args=dict(backend='disk'), type='mmdet.LoadImageFromFile'),
    dict(box_type='qbox', type='mmdet.LoadAnnotations', with_bbox=True),
    dict(box_type_mapping=dict(gt_bboxes='rbox'), type='ConvertBoxType'),
    dict(keep_ratio=True, scale=(
        2560,
        1920,
    ), type='mmdet.Resize'),
    dict(
        direction=[
            'horizontal',
            'vertical',
            'diagonal',
        ],
        prob=0.75,
        type='mmdet.RandomFlip'),
    dict(
        angle_range=180,
        prob=0.5,
        rect_obj_labels=[
            9,
            11,
        ],
        type='RandomRotate'),
    dict(
        pad_val=dict(img=(
            114,
            114,
            114,
        )),
        size=(
            2560,
            1920,
        ),
        type='mmdet.Pad'),
    dict(type='mmdet.PackDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='labelTxt/val/',
        data_prefix=dict(img_path='images/val/'),
        data_root=data_root,
        img_shape=(
            2560,
            1920,
        ),
        pipeline=[
            dict(
                file_client_args=dict(backend='disk'),
                type='mmdet.LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                2560,
                1920,
            ), type='mmdet.Resize'),
            dict(
                box_type='qbox', type='mmdet.LoadAnnotations', with_bbox=True),
            dict(
                box_type_mapping=dict(gt_bboxes='rbox'),
                type='ConvertBoxType'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    2560,
                    1920,
                ),
                type='mmdet.Pad'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='mmdet.PackDetInputs'),
        ],
        test_mode=True,
        type='DOTADataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(metric='mAP', type='DOTAMetric')
val_pipeline = [
    dict(
        file_client_args=dict(backend='disk'), type='mmdet.LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        2560,
        1920,
    ), type='mmdet.Resize'),
    dict(box_type='qbox', type='mmdet.LoadAnnotations', with_bbox=True),
    dict(box_type_mapping=dict(gt_bboxes='rbox'), type='ConvertBoxType'),
    dict(
        pad_val=dict(img=(
            114,
            114,
            114,
        )),
        size=(
            2560,
            1920,
        ),
        type='mmdet.Pad'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='mmdet.PackDetInputs'),
]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='RotLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work'

**Comment by kc-w** [comment]
使用1024 x 1024的图片训练却不会报错

**Comment by kc-w** [comment]
是我的数据集有问题导致的
