### ISSUE TITLE
[Bug] Error in backward() when using psc.

### ISSUE THREAD

**Issue by gbdjxgp** [open-mmlab/mmrotate#919]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: win32
Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.124
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30151 版
GCC: n/a
PyTorch: 2.0.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREAD
POOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.2
OpenCV: 4.8.0
MMEngine: 0.8.1
MMRotate: 1.0.0rc1+

### Reproduces the problem - code sample

dataset:(It's a simple DOTA format dataset that only contains one image in the training set.)[fair_test.zip](https://github.com/open-mmlab/mmrotate/files/12471780/fair_test.zip)

1. Using the model config `configs/psc/rotated-retinanet-rbox-le90_r50_fpn_psc-dual_amp-1x_dota.py`
2. Adding `shield_reg_angle = True` in bbox_head
3. Changing `batch_size=2`; `drop_last=False` in train_dataloader
4. Make sure that batch_data is less than 2 while training.

### Reproduces the problem - command or script

`python tools\train.py --configs/psc/c-rotated-retinanet-rbox-le90_r50_fpn_psc-dual_amp-1x_dota.py`

### Reproduces the problem - error message

Traceback (most recent call last):
  File "C:\code\mmrotate\tools\train.py", line 122, in <module>
    main()
  File "C:\code\mmrotate\tools\train.py", line 118, in main
    runner.train()
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\runner\runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\runner\loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\runner\loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\model\base_model\base_model.py", line 116, in train_step
    optim_wrapper.update_params(parsed_losses)
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\optim\optimizer\optimizer_wrapper.py", line 200, in update_params
    self.backward(loss)
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\mmengine\optim\optimizer\amp_optimizer_wrapper.py", line 125, in backward
    self.loss_scaler.scale(loss).backward(**kwargs)
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "C:\Users\GBDJ\.conda\envs\mmrotate\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2304, 5]] is at version 5; expected version 4 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### Additional information

It seems that line 168 `bbox_weights[:, -1] = 0.` in file angle_branch_retina_head.py make these error.
https://github.com/open-mmlab/mmrotate/blob/350099480693d9a11a60d00ab828fb2aee2d12c5/mmrotate/models/dense_heads/angle_branch_retina_head.py#L167
When setting `shield_reg_angle = False`, it's working usually.

**Comment by gbdjxgp** [comment]
this error still exists in the newest version of mmrotate.
