### ISSUE TITLE
when i  test and visualize the results,a bug happens:TypeError: Visualizer.add_datasample() got an unexpected keyword argument 'pred_score_thr' 

### ISSUE THREAD

**Issue by Czs99** [open-mmlab/mmrotate#936]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu116
OpenCV: 4.7.0
MMEngine: 0.7.2
MMRotate: 1.0.0rc1+

### Reproduces the problem - code sample

python ./tools/test.py \
./configs/h2rbox_v2/h2rbox_v2-le90_r50_fpn-150_rssdd.py \
./work_dirs/h2rbox_v2-le90_r50_fpn-150_rssdd/epoch_84.pth \
--show-dir vis

### Reproduces the problem - command or script

python ./tools/test.py \
./configs/h2rbox_v2/h2rbox_v2-le90_r50_fpn-150_rssdd.py \
./work_dirs/h2rbox_v2-le90_r50_fpn-150_rssdd/epoch_84.pth \
--show-dir vis

### Reproduces the problem - error message

Loads checkpoint by local backend from path: ./work_dirs/h2rbox_v2-le90_r50_fpn-150_rssdd/epoch_84.pth
09/10 12:36:16 - mmengine - INFO - Load checkpoint from ./work_dirs/h2rbox_v2-le90_r50_fpn-150_rssdd/epoch_84.pth
09/10 12:36:17 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "optim_wrapper" registry tree. As a workaround, the current "optim_wrapper" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
09/10 12:36:17 - mmengine - INFO - resumed epoch: 84, iter: 9744
/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/remote-home/czs/h2-mmrotate/./tools/test.py", line 127, in <module>
    main()
  File "/remote-home/czs/h2-mmrotate/./tools/test.py", line 123, in main
    runner.test()
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1752, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "/remote-home/czs/anaconda3/envs/openmmlab1/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1770, in call_hook
    raise TypeError(f'{e} in {hook}') from None
TypeError: Visualizer.add_datasample() got an unexpected keyword argument 'pred_score_thr' in <mmdet.engine.hooks.visualization_hook.DetVisualizationHook object at 0x7fa5f6450f70>

### Additional information

i use the SSDD datasets

**Comment by gaotiexinqu** [comment]
我遇到了同样的问题，我检查了mmengine最新的版本，self._visualizer.add_datasample()函数中仍然没有添加相关参数

**Comment by Venquieu** [comment]
> 我遇到了同样的问题，我检查了mmengine最新的版本，self._visualizer.add_datasample()函数中仍然没有添加相关参数

You should use `DetLocalVisualizer` in `mmdet.visualization` rather than `Visualizer` in  `mmengine.visualization`

**Comment by daxel123** [comment]
hello, I'm facing the same error, in which script I should make the changes to avoid the issue, I did it in visual_hook.py, changing the recommended function and another error appear. thanks in advance

**Comment by J3698** [comment]
For other people who may see this and didn't understand what to change, I changed mmdet/engine/hooks/visualization_hook.py as follows:

add import:
from mmdet.visualization import DetLocalVisualizer

modify DetVisualizationHook's __init__:

DetLocalVisualizer.get_instance('current_visualizer')
self._visualizer = DetLocalVisualizer.get_current_instance()


Another fix could be to change "visualizer" in your config (maybe that's the right fix), but I'll leave that to someone else.
