### ISSUE TITLE
 id_list, dets_list = self.merge_det(results, nproc)  ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by XiaoBzi** [open-mmlab/mmrotate#949]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

install all the requirement as the writer says.

### Reproduces the problem - code sample

python ./tools/test.py  configs/lsknet/lsk_s_ema_fpn_1x_dota_le90.py checkpoints/lsk_s_ema_fpn_1x_dota_le90_20230212-30ed4041.pth --format-only --eval-options submission_dir=work_dirs/Task1_results

Traceback (most recent call last):
  File "D:\遥感\code\LSKNet-main\tools\test.py", line 263, in <module>
    main()
  File "D:\遥感\code\LSKNet-main\tools\test.py", line 245, in main
    dataset.format_results(outputs, **kwargs)
  File "d:\遥感\code\lsknet-main\mmrotate\datasets\dota.py", line 327, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

### Reproduces the problem - command or script

I have change the data root and test the DOTA dataset as the way which the writer has wrote in the readme.
But the problem happens as mentioned above,if anyone can help me?

### Reproduces the problem - error message

python ./tools/test.py  configs/lsknet/lsk_s_ema_fpn_1x_dota_le90.py checkpoints/lsk_s_ema_fpn_1x_dota_le90_20230212-30ed4041.pth --format-only --eval-options submission_dir=work_dirs/Task1_results

Traceback (most recent call last):
  File "D:\遥感\code\LSKNet-main\tools\test.py", line 263, in <module>
    main()
  File "D:\遥感\code\LSKNet-main\tools\test.py", line 245, in main
    dataset.format_results(outputs, **kwargs)
  File "d:\遥感\code\lsknet-main\mmrotate\datasets\dota.py", line 327, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

### Additional information

I have change the data root and test the DOTA dataset as the way which the writer has wrote in the readme.
But the problem happens as mentioned above,if anyone can help me?

**Comment by tom123478** [comment]
请问您解决了吗？

**Comment by Joey-He** [comment]
请问您解决了吗？

**Comment by Joey-He** [comment]
看看你data_root的路径是否正确 你这是没有读到test中的images

**Comment by kaunghtetsan275** [comment]
For me, I had to change the `data_root` path in model config file in config/<model_name>.py to solve it. It was quite a headache for me to figure it out as well.

**Comment by Crystal-Zhang97** [comment]
I also encountered this issue but have since resolved it. The problem stemmed from the test set data not being split. To fix this, everyone should run python `mmrotate/tools/data/dota/split/img_split.py --base-json mmrotate/tools/data/dota/split/split_configs/ss_test.json`. Once this is done, the process should be successful.
