### ISSUE TITLE
[Bug]   if device.type == "cpu":

### ISSUE THREAD

**Issue by ning-feng** [open-mmlab/mmrotate#978]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

torch                  2.1.2
torchvision            0.16.2
cuda                      12.1
mmcv-full              1.7.1

### Reproduces the problem - code sample

.

### Reproduces the problem - command or script

python tools/train.py configs/redet/redet_re50_refpn_3x_hrsc_le90.py --work-dir result --gpu-ids 0

### Reproduces the problem - error message

2023-12-27 17:05:25,231 - mmrotate - INFO - workflow: [('train', 1)], max: 36 epochs
2023-12-27 17:05:25,231 - mmrotate - INFO - Checkpoints will be saved to D:\workSpace\pycharm\mmrotate-main\result by HardDiskBackend.     
D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in whi
ch it will remove components related to the training process and add a data transformation module. In addition, it will rename the package 
names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in whi
ch it will remove components related to the training process and add a data transformation module. In addition, it will rename the package 
names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 183, in main
    train_detector(
  File "d:\workspace\pycharm\mmrotate-main\mmrotate\apis\train.py", line 144, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\parallel\data_parallel.py", line 76, in train_step
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
    streams = [_get_stream(device) for device in target_gpus]
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\mmcv\parallel\_functions.py", line 75, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "D:\software\anoconda\envs\mmrotate\lib\site-packages\torch\nn\parallel\_functions.py", line 117, in _get_stream
    if device.type == "cpu":
AttributeError: 'int' object has no attribute 'type'

### Additional information

我是新配置的环境第一次使用mmrotate,可能某个地方配置错误。
I'm using mmrotate for the first time in a newly configured environment, and there may be a misconfiguration somewhere.

**Comment by Jimmy1456** [comment]
same issue, but cuda 11.8 works.

**Comment by IacopoFerrari** [comment]
Same issue.. has someone solved it in cuda 12.1?

**Comment by Pluviophile-sy** [comment]
> 在最新版本（[master](https://github.com/open-mmlab/mmrotate)）中也有同样的问题，但[最新版本（1.x）](https://github.com/open-mmlab/mmrotate/tree/dev-1.x)有效
The same problem, but when I use the latest version of mmrotate, there is no new problem. How do you solve it?
![image](https://github.com/open-mmlab/mmrotate/assets/140753006/4bb0c147-f968-495d-9d5b-2f26284784fc)

**Comment by None5411** [comment]
same issue，have you solved this problem？or just the problem about version？

**Comment by Morningstaripfy** [comment]
cuda111/116: mmcv-1.6.1 mmdet-2.x mmrotate 0.x
cuda118/120:mmcv-2 mmdet-3 mmrotate-1

**Comment by Morningstaripfy** [comment]
> same issue，have you solved this problem？or just the problem about version？

cuda111/116: mmcv-1.6.1 mmdet-2.x mmrotate 0.x
cuda118/120:mmcv-2 mmdet-3 mmrotate-1

**Comment by None5411** [comment]
> > same issue，have you solved this problem？or just the problem about version？
> 
> cuda111/116: mmcv-1.6.1 mmdet-2.x mmrotate 0.x cuda118/120:mmcv-2 mmdet-3 mmrotate-1

i did't solve  the issue in the version you gived,but i finally solve this in https://zhuanlan.zhihu.com/p/674887894
Thanks for your help

**Comment by 231055558** [comment]
> > > same issue，have you solved this problem？or just the problem about version？
> > 
> > 
> > cuda111/116: mmcv-1.6.1 mmdet-2.x mmrotate 0.x cuda118/120:mmcv-2 mmdet-3 mmrotate-1
> 
> i did't solve the issue in the version you gived,but i finally solve this in https://zhuanlan.zhihu.com/p/674887894 Thanks for your help

Thank you for your sharing. I successfully completed the environment configuration according to the post you shared. My system environment is windows11+cuda11.8/12.2, and the configuration can be successfully completed by following the post operation

**Comment by amrzv** [comment]
This error still occurs in [MMRotate_Tutorial.ipynb](https://colab.research.google.com/github/open-mmlab/mmrotate/blob/main/demo/MMRotate_Tutorial.ipynb#scrollTo=7WBWHu010PN3).

**Comment by ejds123456** [comment]
https://blog.csdn.net/weixin_45716425/article/details/143797917 我根据这个修改成功了
